name: 'Upload Versions'
description: 'Upload version information for public packages'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: 22
    - name: Write workspace versions as JSON file
      uses: actions/github-script@a3e7071a34d7e1f219a8a4de9a5e0a34d1ee1293
      with:
        script: |
          const fs = require('node:fs');

          const globber = glob.create(['packages/**/package.json', '!**/node_modules/**'].join('\n'))
          const packageJsonPaths = await globber.glob()
          const output = {
            packages: [],
          };

          for (const packageJsonPath of packageJsonPaths) {
            const contents = fs.readFileSync(packageJsonPath, 'utf8');
            const packageJson = JSON.parse(contents);
            if (packageJson.private) {
              continue;
            }

            const pkg = {
              name: packageJson.name,
              version: packageJson.version,
            };
            output.packages.push(pkg);
          }

          fs.writeFileSync('versions.json', JSON.stringify(output, null, 2));
    - name: Upload version file
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: versions
        path: versions.json
