import React from 'react'
import {CounterLabel} from '../../src'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CounterLabel,
  'https://www.figma.c1om/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=18959-64970&t=9imbqLYmermiHP7U-4',
  {
    props: {
      variant: figma.enum('variant', {
        primary: 'primary',
        secondary: 'secondary',
      }),
      count: figma.textContent('text'),
    },
    example: ({variant, count}) => <CounterLabel scheme={variant}>{count}</CounterLabel>,
  },
)
