const data = {
  issue: {
    labelIds: ['MDU6TGFiZWw4Mzk2MzgxMTU=', 'MDU6TGFiZWw4Mzk2MzgxMjE='],
    assigneeIds: ['MDQ6VXNlcjQxNzI2OA==', 'MDQ6VXNlcjE0NDY1MDM=', 'MDQ6VXNlcjE4NjM3NzE='],
  },
  ref: 'main',
  collaborators: [
    {
      id: 'MDQ6VXNlcjQxNzI2OA==',
      name: 'Pavithra Kodmad',
      login: 'pksjce',
      recommended: true,
    },
    {
      id: 'MDQ6VXNlcjE0NDY1MDM=',
      name: 'Armağan',
      login: 'broccolinisoup',
      recommended: true,
    },
    {
      id: 'MDQ6VXNlcjE4NjM3NzE=',
      name: 'Siddharth Kshetrapal',
      login: 'siddharthkp',
    },
    {
      id: 'MDQ6VXNlcjIzMTM5OTg=',
      name: 'Mike Perrotti',
      login: 'mperrotti',
    },
    {
      id: 'MDQ6VXNlcjM5MDE3NjQ=',
      name: 'Josh Black',
      login: 'joshblack',
      recommended: true,
    },
    {
      id: 'MDQ6VXNlcjE4NjYxMDMw',
      name: 'Katie Langerman',
      login: 'langermank',
    },
    {
      id: 'MDQ6VXNlcjU3NTI4MA==',
      name: 'Cameron Dutro',
      login: 'camertron',
    },
  ],
  labels: [
    {
      color: 'd73a4a',
      id: 'MDU6TGFiZWw4Mzk2MzgxMTU=',
      name: 'bug',
      description: "Something isn't working",
      createdAt: '2018-02-17T00:09:05Z',
    },
    {
      color: 'cfd3d7',
      id: 'MDU6TGFiZWw4Mzk2MzgxMTY=',
      name: 'duplicate',
      description: 'This issue or pull request already exists',
      createdAt: '2018-02-17T00:09:05Z',
    },
    {
      color: 'a2eeef',
      id: 'MDU6TGFiZWw4Mzk2MzgxMTc=',
      name: 'enhancement',
      description: 'New feature or request',
      createdAt: '2018-02-17T00:09:05Z',
    },
    {
      color: 'd876e3',
      id: 'MDU6TGFiZWw4Mzk2MzgxMjE=',
      name: 'futher info needed',
      description: 'Further information is requested',
      createdAt: '2018-02-17T00:09:05Z',
    },
    {
      color: '7057ff',
      id: 'MDU6TGFiZWw4Mzk2MzgxMTk=',
      name: 'good first issue',
      description: 'Good for newcomers',
      createdAt: '2018-02-17T00:09:05Z',
    },
    {
      color: '008672',
      id: 'MDU6TGFiZWw4Mzk2MzgxMTg=',
      name: 'up for grabs',
      description: "anyone can take on this work, it's ready to go",
      createdAt: '2018-02-17T00:09:05Z',
    },
    {
      color: 'ffffff',
      id: 'MDU6TGFiZWw4Mzk2MzgxMjI=',
      name: 'wontfix',
      description: 'This will not be worked on',
      createdAt: '2018-02-17T00:09:05Z',
    },
    {
      color: 'FFD2ED',
      id: 'MDU6TGFiZWw4ODkxNjUwNzU=',
      name: '💓collab',
      description: 'a vibrant hub of collaboration',
      createdAt: '2018-04-03T21:03:53Z',
    },
    {
      color: '9eea90',
      id: 'MDU6TGFiZWw5NDAyMzcyOTU=',
      name: 'status: wip',
      description: '',
      createdAt: '2018-05-21T19:11:15Z',
    },
    {
      color: 'eae658',
      id: 'MDU6TGFiZWw5NDAyMzc1NzY=',
      name: 'status: review needed',
      description: '',
      createdAt: '2018-05-21T19:11:36Z',
    },
    {
      color: 'a9abe8',
      id: 'MDU6TGFiZWw5NDA1MDc5NzQ=',
      name: 'type: discussion',
      description: '',
      createdAt: '2018-05-22T02:06:49Z',
    },
    {
      color: '86181d',
      id: 'MDU6TGFiZWw5NDg2NDM1MzI=',
      name: '🚧 blocked',
      description: 'Someone or something is preventing this from moving forward',
      createdAt: '2018-05-29T22:02:54Z',
    },
    {
      color: '1d76db',
      id: 'MDU6TGFiZWwxMDI2NDE1MTYw',
      name: 'docs',
      description: 'Documentation',
      createdAt: '2018-08-16T16:35:43Z',
    },
    {
      color: 'fcc0dc',
      id: 'MDU6TGFiZWwxMDU3MjcwNzA4',
      name: 'patch release',
      description: 'bug fixes, docs, housekeeping',
      createdAt: '2018-09-14T20:27:34Z',
    },
    {
      color: 'ff73b4',
      id: 'MDU6TGFiZWwxMDU3MjcxMDUz',
      name: 'minor release',
      description: 'new features',
      createdAt: '2018-09-14T20:28:01Z',
    },
    {
      color: 'e3006a',
      id: 'MDU6TGFiZWwxMDU3MjcxNDE5',
      name: 'major release',
      description: 'breaking changes',
      createdAt: '2018-09-14T20:28:30Z',
    },
    {
      color: '107d93',
      id: 'MDU6TGFiZWwxMDU3MjczMjkz',
      name: 'deployment',
      description: '',
      createdAt: '2018-09-14T20:31:10Z',
    },
    {
      color: 'd4c5f9',
      id: 'MDU6TGFiZWwxMzgyNTYyNjQ0',
      name: 'accessibility',
      description: '',
      createdAt: '2019-05-29T19:56:35Z',
    },
    {
      color: '0366d6',
      id: 'MDU6TGFiZWwxNjE2MTQ5MDE2',
      name: 'dependencies',
      description: 'Pull requests that update a dependency file',
      createdAt: '2019-10-14T18:19:49Z',
    },
    {
      color: 'e1e4e8',
      id: 'MDU6TGFiZWwxNjU3MjI0NTcw',
      name: 'fr-skip',
      description: 'Remove this from the Design Systems first responder list',
      createdAt: '2019-11-04T18:18:03Z',
    },
    {
      color: 'fcba03',
      id: 'MDU6TGFiZWwxNzkwMDY4Mzk5',
      name: 'developer experience',
      description: '',
      createdAt: '2020-01-15T22:30:35Z',
    },
    {
      color: '68f9cc',
      id: 'MDU6TGFiZWwxNzkwMDY4NDg1',
      name: 'contributor experience',
      description: '',
      createdAt: '2020-01-15T22:30:41Z',
    },
    {
      color: 'a1b220',
      id: 'MDU6TGFiZWwxNzkwMDcyODY5',
      name: 'API',
      description: '',
      createdAt: '2020-01-15T22:34:09Z',
    },
    {
      color: '6494f4',
      id: 'MDU6TGFiZWwxNzkxNjM5MzM1',
      name: 'new component',
      description: '',
      createdAt: '2020-01-16T16:13:35Z',
    },
    {
      color: 'f48b96',
      id: 'MDU6TGFiZWwxOTg5MDAwNjk0',
      name: 'experimental',
      description: '',
      createdAt: '2020-04-15T20:52:13Z',
    },
    {
      color: 'db9360',
      id: 'MDU6TGFiZWwxOTkzNTcwNzUx',
      name: 'design',
      description: '',
      createdAt: '2020-04-17T15:08:45Z',
    },
    {
      color: 'F9D0C4',
      id: 'MDU6TGFiZWwyNjkzNTE0OTQw',
      name: 'coverage',
      description: '',
      createdAt: '2021-01-27T22:25:23Z',
    },
    {
      color: '077CA4',
      id: 'MDU6TGFiZWwyNjkzNTE5NTc1',
      name: 'epic',
      description: '',
      createdAt: '2021-01-27T22:27:57Z',
    },
    {
      color: 'F9D0C4',
      id: 'MDU6TGFiZWwyNjkzNTMwODUy',
      name: 'behaviors',
      description: '',
      createdAt: '2021-01-27T22:34:49Z',
    },
    {
      color: '1d76db',
      id: 'MDU6TGFiZWwyNzkzMjYwMTgz',
      name: 'typescript',
      description: '',
      createdAt: '2021-03-04T20:17:59Z',
    },
    {
      color: 'DBEDFF',
      id: 'MDU6TGFiZWwzMzA5MjY0Nzcz',
      name: 'size: sand',
      description: '',
      createdAt: '2021-08-31T02:08:34Z',
    },
    {
      color: 'DBEDFF',
      id: 'MDU6TGFiZWwzMzA5MjY1MDM2',
      name: 'size: pebble',
      description: '',
      createdAt: '2021-08-31T02:08:42Z',
    },
    {
      color: 'DBEDFF',
      id: 'MDU6TGFiZWwzMzA5MjY1MTc4',
      name: 'size: rock',
      description: '',
      createdAt: '2021-08-31T02:08:49Z',
    },
    {
      color: 'DBEDFF',
      id: 'MDU6TGFiZWwzMzA5MjY1NTg3',
      name: 'size: boulder',
      description: '',
      createdAt: '2021-08-31T02:09:00Z',
    },
    {
      color: 'ededed',
      id: 'MDU6TGFiZWwzMzE4NjA1ODgy',
      name: 'Stale',
      description: null,
      createdAt: '2021-09-02T22:04:15Z',
    },
    {
      color: '0052CC',
      id: 'LA_kwDOB0K8ws7Oq_eD',
      name: 'react',
      description: '',
      createdAt: '2021-10-19T16:48:08Z',
    },
    {
      color: 'eeeeee',
      id: 'LA_kwDOB0K8ws7O4h4u',
      name: 'skip changeset',
      description: '',
      createdAt: '2021-10-20T16:15:21Z',
    },
    {
      color: 'D93F0B',
      id: 'LA_kwDOB0K8ws7WuYLd',
      name: 'do not merge',
      description: '',
      createdAt: '2021-12-01T19:02:44Z',
    },
    {
      color: 'e5534b',
      id: 'LA_kwDOB0K8ws73bq-W',
      name: 'needs triage',
      description: '',
      createdAt: '2022-05-20T13:41:47Z',
    },
    {
      color: 'B60205',
      id: 'LA_kwDOB0K8ws8AAAABA3IfBw',
      name: 'a11y-eng-secondary',
      description: '',
      createdAt: '2022-07-22T10:04:29Z',
    },
    {
      color: 'ffffff',
      id: 'LA_kwDOB0K8ws8AAAABBfG7EQ',
      name: 'support',
      description: 'Tasks where the team is supporting and helping other teams',
      createdAt: '2022-08-04T15:33:56Z',
    },
    {
      color: 'DDF4FF',
      id: 'LA_kwDOB0K8ws8AAAABG14Q1Q',
      name: 'component: tree view',
      description: 'Issues related to the TreeView component',
      createdAt: '2022-11-02T18:49:40Z',
    },
    {
      color: 'DDF4FF',
      id: 'LA_kwDOB0K8ws8AAAABHLXdxw',
      name: 'component: SplitPageLayout',
      description: 'Issues related to the PageLayout and SplitPageLayout components',
      createdAt: '2022-11-08T18:57:47Z',
    },
    {
      color: 'DDF4FF',
      id: 'LA_kwDOB0K8ws8AAAABHLXucw',
      name: 'component: nav list',
      description: 'Issues related to the NavList component',
      createdAt: '2022-11-08T18:58:49Z',
    },
    {
      color: 'DDF4FF',
      id: 'LA_kwDOB0K8ws8AAAABHLYCfQ',
      name: 'component: button',
      description: 'Issues related to the Button component',
      createdAt: '2022-11-08T19:00:13Z',
    },
  ],
  users: [
    {
      id: 'MDQ6VXNlcjQxNzI2OA==',
      name: 'Pavithra Kodmad',
      login: 'pksjce',
    },
    {
      id: 'MDQ6VXNlcjE0NDY1MDM=',
      name: 'Armağan',
      login: 'broccolinisoup',
    },
    {
      id: 'MDQ6VXNlcjE4NjM3NzE=',
      name: 'Siddharth Kshetrapal',
      login: 'siddharthkp',
    },
    {
      id: 'MDQ6VXNlcjIzMTM5OTg=',
      name: 'Mike Perrotti',
      login: 'mperrotti',
    },
    {
      id: 'MDQ6VXNlcjM5MDE3NjQ=',
      name: 'Josh Black',
      login: 'joshblack',
    },
    {
      id: 'MDQ6VXNlcjE4NjYxMDMw',
      name: 'Katie Langerman',
      login: 'langermank',
    },
    {
      id: 'MDQ6VXNlcjU3NTI4MA==',
      name: 'Cameron Dutro',
      login: 'camertron',
    },
  ],
  branches: [
    {id: 'main', name: 'main', trailingInfo: 'Default'},
    {id: 'next-major', name: 'next-major'},
    {id: 'changeset-release/main', name: 'changeset-release/main'},
    {id: 'changeset-release/next-major', name: 'changeset-release/next-major'},
    {id: 'selectpanel-2', name: 'selectpanel-2'},
    {id: 'bs/actionlist-heading', name: 'bs/actionlist-heading'},
    {id: 'refactor/support-alt-names', name: 'refactor/support-alt-names'},
    {id: 'fix/update-action-list', name: 'fix/update-action-list'},
    {id: 'dependabot/markdownlint-github-0.4.1', name: 'dependabot/markdownlint-github-0.4.1'},
  ],
  tags: [
    {id: 'v35.31.0', name: 'v35.31.0', trailingInfo: 'Latest'},
    {id: 'v35.30.0', name: 'v35.30.0'},
    {id: 'v35.29.0', name: 'v35.29.0'},
    {id: 'v35.28.0', name: 'v35.28.0'},
    {id: 'v35.27.1', name: 'v35.27.1'},
    {id: 'v35.27.0', name: 'v35.27.0'},
    {id: 'v35.26.1', name: 'v35.26.1'},
    {id: 'v35.26.0', name: 'v35.26.0'},
    {id: 'v35.0.0', name: 'v35.0.0'},
    {id: 'v34.0.0', name: 'v34.0.0'},
  ],
  repos: [
    {
      org: 'github',
      name: 'primer',
      description: "The internal hub for GitHub's open-source design system",
    },
    {
      org: 'github',
      name: 'github',
      description: 'You’re lookin’ at it.',
    },
    {
      org: 'primer',
      name: 'react',
      description: "An implementation of GitHub's Primer Design System using React",
    },
    {
      org: 'primer',
      name: 'primitives',
      description: 'Color, typography, and spacing primitives in json',
    },
    {
      org: 'primer',
      name: 'brand',
      description: 'React components and Primitives for GitHub marketing websites',
    },
    {
      org: 'facebook',
      name: 'react',
      description: 'The library for web and native user interfaces',
    },
    {
      org: 'primer',
      name: 'view_components',
      description: 'ViewComponents for the Primer Design System',
    },
  ],
  pulls: [
    {
      id: '4286',
      name: 'chore(deps): bump @mdx-js/mdx from 1.6.22 to 3.0.1',
      description: 'Opened 14 hours ago',
      status: 'open',
    },
    {id: '4278', name: 'Address a few v8 color bugs', description: 'Opened 4 days ago', status: 'open'},
    {id: '4277', name: 'SelectPanel2: Responsive variants', description: 'Opened 4 days ago', status: 'draft'},
    {
      name: 'SelectPanel2: Submit panel when an item is selected with Enter',
      id: '4265',
      description: 'Merged last week',
      status: 'merged',
    },
    {
      name: 'test(e2e): add e2e test for SelectPanel2 default story',
      id: '4279',
      description: 'Opened 3 days ago',
      status: 'open',
    },
  ],
}

export default data
