import './global.css'
import {ThemeProvider, BaseStyles} from '@primer/styled-react'
import {FeatureFlags} from '@primer/react/experimental'
import {StyledComponentsRegistry} from './registry'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    // Note: the focus-visible polyfill adds additional attributes to `html`
    // that cause hydration mismatch errors
    <html lang="en" suppressHydrationWarning>
      <body>
        <FeatureFlags flags={{primer_react_use_styled_react_theming: true}}>
          <StyledComponentsRegistry>
            <ThemeProvider>
              <BaseStyles>{children}</BaseStyles>
            </ThemeProvider>
          </StyledComponentsRegistry>
        </FeatureFlags>
      </body>
    </html>
  )
}
