import React from 'react'
import {TextInput} from './TextInput'
import figma from '@figma/code-connect'
import FormControl from '../FormControl'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TextInput,
  'https://www.figma.com/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=15341-46504&t=39jWyeflbJqVh77d-4',
  {
    props: {
      inputTextDisabled: figma.instance('inputTextDisabled'),
      trailingActionDisabled: figma.instance('trailingActionDisabled'),
      inputTextType: figma.instance('inputTextType'),
      hasLabel: figma.boolean('label?'),
      trailingAction: figma.instance('trailingAction'),
      trailingAction: figma.boolean('➡️ trailingAction?'),
      icon: figma.instance('icon'),
      leadingVisual: figma.boolean('⬅️ leadingVisual?'),
      caption: figma.boolean('caption?'),
      size: figma.enum('size', {
        small: 'small',
        medium: 'medium',
        large: 'large',
      }),
      state: figma.enum('state', {
        rest: 'rest',
        focus: 'focus',
        disabled: 'disabled',
        'read-only': 'read-only',
      }),
      validation: figma.enum('validation', {
        none: 'none',
        invalid: <InlineMessage type="error" />,
        success: 'success',
      }),
      inset: figma.boolean('inset?'),
      label: figma.children(['Label']),
      validationMessage: figma.children(['_InlineValidationMessage']),
    },
    example: ({label, size, validation}) => (
      // TextInput and FormControl.Label must be direct children of FormControl
      <>
        {label}
        <TextInput size={size} />
        {validation}
      </>
    ),
  },
)

figma.connect(
  FormControl.Label,
  'https://www.figma.com/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=15341-46399&t=8s7g8y2Te97Vxmv7-4',
  {
    props: {},
    example: () => <FormControl.Label>Label Text</FormControl.Label>,
  },
)
