import React from 'react'
import BranchName from './BranchName'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BranchName,
  'https://www.figma.com/file/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?type=design&node-id=3655-7208&mode=design&t=HqwKHI6akvFT5reK-4',
  {
    props: {
      type: figma.enum('type', {
        default: 'default',
        link: 'link',
      }),
      leadingIcon: figma.boolean('leadingIcon?'),
    },
    example: () => <BranchName />,
  },
)
