// Mock data for the RefPickerV1Correct example. Not part of the component's
// product logic — supplied to the component as props in the Storybook story.

export const branches: string[] = [
  'main',
  'develop',
  'release/2.0',
  'release/1.9',
  'feature/select-panel-tabs',
  'feature/ref-picker',
  'feature/virtualized-list',
  'feature/a11y-audit',
  'fix/overlay-focus-trap',
  'fix/listbox-aria',
  'fix/keyboard-nav',
  'chore/bump-deps',
  'chore/storybook-9',
  'docs/contributing',
  'docs/adr-overlay',
  'experiment/css-modules',
  'experiment/sx-removal',
  'hotfix/prod-regression',
  'wip/design-tokens',
  'wip/theme-refactor',
  'renovate/octicons',
  'renovate/typescript-5',
  'dependabot/npm/react-19',
  'gh-pages',
]

export const tags: string[] = [
  'v2.0.0',
  'v1.9.4',
  'v1.9.3',
  'v1.9.2',
  'v1.9.1',
  'v1.9.0',
  'v1.8.0',
  'v1.7.2',
  'v1.7.1',
  'v1.7.0',
  'v1.6.0',
  'v1.5.0',
  'v1.4.0',
  'v1.0.0',
  'v0.9.0-rc.2',
  'v0.9.0-rc.1',
  'nightly-2024-06-01',
  'nightly-2024-05-15',
  'release-candidate',
  'stable',
]
