name: Build and Cache storybook
description: Storybook cache workflow
runs:
  using: composite
  steps:
    - name: Restore cached storybook
      id: cache-storybook-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          packages/react/storybook-static
          docs/
        key: ${{ runner.os }}-storybook-${{github.run_id}}
    - if: steps.cache-storybook-restore.outputs.cache-hit != 'true'
      shell: bash
      name: Build docs
      run: npm run build:docs:preview
    - if: steps.cache-storybook-restore.outputs.cache-hit != 'true'
      shell: bash
      name: Build storybook
      run: npx storybook build
      working-directory: packages/react/
    - if: steps.cache-storybook-restore.outputs.cache-hit != 'true'
      name: Save storybook
      id: cache-storybook-save
      uses: actions/cache/save@v4
      with:
        path: |
          packages/react/storybook-static
          docs/
        key: ${{ steps.cache-storybook-restore.outputs.cache-primary-key }}
