name: 'Check for Changed Files'
description: 'Require changed files in a pull request'
inputs:
  file-pattern:
    description: 'Glob pattern for changed file to check for'
    required: true
  prereq-pattern:
    description: 'Glob pattern that guards whether the action will run'
    required: false
    default: '**'
  skip-label:
    description: 'Label to trigger skipping the check'
    required: false
    default: ''
  failure-message:
    description: 'String template used when the check fails'
    required: false
    default: 'the prerequisite file pattern ${prereq-pattern} matched changed files in the pull request, but the ${file-pattern} pattern did NOT and the ${skip-label} label is not set'
  token:
    description: 'GitHub token to use to list the pull request files'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'index.js'
