import React from 'react'
import {ProgressBar, Item as ProgressBarItem} from './ProgressBar'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ProgressBar,
  'https://www.figma.com/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=16443-62464&t=39jWyeflbJqVh77d-11',
  {
    props: {
      size: figma.enum('size', {
        small: 'small',
        medium: 'default',
        large: 'large',
      }),
      children: figma.children(['_ProgressBar.item', '_ProgressBar.item', '_ProgressBar.item']),
    },
    example: ({size, children}) => (
      <ProgressBar barSize={size} progress="...">
        {children}
      </ProgressBar>
    ),
  },
)

figma.connect(
  ProgressBarItem,
  'https://www.figma.com/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=34334-68158&t=ZDPd1N3qXGmK3Jif-4',
  {
    props: {
      color: figma.enum('color', {
        green: '--data-green-color',
        teal: '--data-teal-color',
        blue: '--data-blue-color',
        purple: '--data-purple-color',
        orange: '--data-orange-color',
        red: '--data-red-color',
        pink: '--data-pink-color',
        yellow: '--data-yellow-color',
        auburn: '--data-auburn-color',
        gray: '--data-gray-color',
      }),
    },
    example: ({color}) => <ProgressBarItem sx={color} />,
  },
)
