import React from 'react'
import {Heading} from './Heading'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Heading,
  'https://www.figma.com/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=21069-78785&t=LhKEppN9LJfzQQ49-4',
  {
    props: {
      text: figma.textContent('Text'),
      variant: figma.enum('variant', {
        large: 'large',
        medium: 'medium',
        small: 'small',
      }),
    },
    example: ({text, variant}) => <Heading variant={variant}>{text}</Heading>,
  },
)
