use anyhow::{Context, Result};
use std::path::Path;
use std::process::Command;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Run a command and return its trimmed stdout.
fn run(program: &str, args: &[&str], cwd: &Path) -> Result<String> {
    let output = Command::new(program)
        .args(args)
        .current_dir(cwd)
        .output()
        .with_context(|| format!("Failed to run `{} {}`", program, args.join(" ")))?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        Err(anyhow::anyhow!(
            "`{} {}` failed (exit {}): {}",
            program,
            args.join(" "),
            output.status,
            stderr.trim()
        ))
    }
}

/// Check whether `version` of `package_name` is already present on the npm
/// registry. Returns `true` if it is already published.
fn already_published(package_name: &str, version: &str) -> bool {
    let spec = format!("{}@{}", package_name, version);
    Command::new("npm")
        .args(["view", &spec, "version", "--json"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

// ---------------------------------------------------------------------------
// `changes publish` command
// ---------------------------------------------------------------------------

pub fn cmd_publish(
    root: &Path,
    filter_packages: &[String],
    tag: &str,
    dry_run: bool,
) -> Result<()> {
    let packages = crate::workspace::discover_packages(root)?;

    let to_publish: Vec<_> = packages
        .iter()
        .filter(|p| {
            // Apply --package filter when provided
            if !filter_packages.is_empty() {
                return filter_packages.iter().any(|f| f == p.name());
            }
            true
        })
        .filter(|p| {
            // Only publish packages that are not yet on the registry at this version
            if already_published(p.name(), p.version()) {
                println!(
                    "  skip {}@{} (already published)",
                    p.name(),
                    p.version()
                );
                false
            } else {
                true
            }
        })
        .collect();

    if to_publish.is_empty() {
        println!("All packages are already up-to-date on npm.");
        return Ok(());
    }

    for pkg in &to_publish {
        println!("Publishing {}@{} [tag={}]…", pkg.name(), pkg.version(), tag);

        if dry_run {
            println!(
                "  [dry-run] would run: npm publish --tag {} --access public",
                tag
            );
        } else {
            run(
                "npm",
                &["publish", "--tag", tag, "--access", "public"],
                &pkg.path,
            )
            .with_context(|| format!("Failed to publish {}", pkg.name()))?;

            println!("  ✓ published {}@{}", pkg.name(), pkg.version());
        }

        // ---- Create git tag ----
        let tag_name = format!("{}@{}", pkg.name(), pkg.version());

        if dry_run {
            println!("  [dry-run] would create git tag: {}", tag_name);
        } else {
            let tag_result = Command::new("git")
                .args(["tag", &tag_name])
                .current_dir(root)
                .status()
                .context("Failed to run git tag")?;

            if !tag_result.success() {
                eprintln!(
                    "  Warning: git tag '{}' already exists or could not be created.",
                    tag_name
                );
            } else {
                println!("  ✓ created git tag {}", tag_name);

                // Push the tag
                let push_result = Command::new("git")
                    .args(["push", "origin", &tag_name])
                    .current_dir(root)
                    .status()
                    .context("Failed to push git tag")?;

                if !push_result.success() {
                    eprintln!("  Warning: failed to push git tag {}.", tag_name);
                }
            }
        }

        // ---- Create GitHub release (autogenerated notes) ----
        let tag_name = format!("{}@{}", pkg.name(), pkg.version());
        let release_title = format!("{} v{}", pkg.name(), pkg.version());

        if dry_run {
            println!(
                "  [dry-run] would create GitHub release: {}",
                release_title
            );
        } else {
            // Use `gh release create` with --generate-notes for auto-generated release notes
            let gh_result = Command::new("gh")
                .args([
                    "release",
                    "create",
                    &tag_name,
                    "--title",
                    &release_title,
                    "--generate-notes",
                ])
                .current_dir(root)
                .status();

            match gh_result {
                Ok(s) if s.success() => println!("  ✓ created GitHub release for {}", tag_name),
                Ok(_) => eprintln!(
                    "  Warning: `gh release create` failed for {}. \
                     Install the GitHub CLI (https://cli.github.com) to create releases.",
                    tag_name
                ),
                Err(_) => eprintln!(
                    "  Warning: `gh` not found. Install the GitHub CLI to create releases."
                ),
            }
        }
    }

    if !dry_run {
        println!("\n✓ Published {} package(s).", to_publish.len());
    } else {
        println!("\n[dry-run] Would publish {} package(s).", to_publish.len());
    }

    Ok(())
}
