contact_links:
  - name: (GitHub staff only) Propose an idea for a new component
    url: https://github.com/github/primer/discussions/categories/design-patterns
    about: If you'd like to propose a new Primer pattern, big or small, let's talk! The best way to get started, especially if your proposal is in its early stages, is to open a pattern proposal (GitHub staff only).
  - name: Request a new pattern
    url: https://github.com/github/primer/issues/new?assignees=&labels=needs+triage&template=01-request.md&title=%5BProposal%5D+
    about: If you're more certain about what you need, please open a pattern request issue (GitHub staff only). We will get back to you after our weekly backlog triaging session.
