import React from 'react'
import {Heading, Popover, Text} from '../../src'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Popover, 'https://www.figma.com/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=19015-63778&m=dev', {
  props: {
    body: figma.string('body'),
    heading: figma.string('heading'),
    action: figma.children('Action'),
  },
  example: ({heading, body, action}) => (
    <Popover>
      <Popover.Content>
        <Heading
          sx={{
            fontSize: 2,
          }}
        >
          {heading}
        </Heading>
        <Text as="p">{body}</Text>
        {action}
      </Popover.Content>
    </Popover>
  ),
})
