module.exports = {
  rules: {
    'a11y-explicit-heading': require('./rules/a11y-explicit-heading'),
    'a11y-link-in-text-block': require('./rules/a11y-link-in-text-block'),
    'a11y-no-duplicate-form-labels': require('./rules/a11y-no-duplicate-form-labels'),
    'a11y-no-title-usage': require('./rules/a11y-no-title-usage'),
    'a11y-remove-disable-tooltip': require('./rules/a11y-remove-disable-tooltip'),
    'a11y-tooltip-interactive-trigger': require('./rules/a11y-tooltip-interactive-trigger'),
    'a11y-use-accessible-tooltip': require('./rules/a11y-use-accessible-tooltip'),
    'direct-slot-children': require('./rules/direct-slot-children'),
    'enforce-button-for-link-with-no-href': require('./rules/enforce-button-for-link-with-no-href'),
    'enforce-css-module-default-import': require('./rules/enforce-css-module-default-import'),
    'enforce-css-module-identifier-casing': require('./rules/enforce-css-module-identifier-casing'),
    'new-color-css-vars': require('./rules/new-color-css-vars'),
    'no-deprecated-entrypoints': require('./rules/no-deprecated-entrypoints'),
    'no-deprecated-experimental-components': require('./rules/no-deprecated-experimental-components'),
    'no-deprecated-props': require('./rules/no-deprecated-props'),
    'no-system-props': require('./rules/no-system-props'),
    'no-unnecessary-components': require('./rules/no-unnecessary-components'),
    'no-use-responsive-value': require('./rules/no-use-responsive-value'),
    'no-wildcard-imports': require('./rules/no-wildcard-imports'),
    'prefer-action-list-item-onselect': require('./rules/prefer-action-list-item-onselect'),
    'spread-props-first': require('./rules/spread-props-first'),
    'use-deprecated-from-deprecated': require('./rules/use-deprecated-from-deprecated'),
    'use-styled-react-import': require('./rules/use-styled-react-import'),
  },
  configs: {
    recommended: require('./configs/recommended'),
  },
}
