import React from 'react'
import {FormControl, Checkbox} from '../../src'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  'https://www.figma.com/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=15341-46321&t=9imbqLYmermiHP7U-4',
  {
    props: {
      caption: figma.boolean('caption?', {
        false: undefined,
        true: figma.children('Caption'),
      }),
      label: figma.children('Label'),
      labelProps: figma.nestedProps('Label', {
        required: figma.boolean('required'),
      }),
      disabled: figma.enum('state', {
        disabled: true,
      }),
      checked: figma.boolean('checked?'),
      indeterminate: figma.boolean('indeterminate?'),
    },
    example: ({disabled, label, caption, checked, indeterminate, labelProps}) => (
      <FormControl disabled={disabled} required={labelProps.required}>
        <Checkbox checked={checked} indeterminate={indeterminate} value="..." />
        {label}
        {caption}
      </FormControl>
    ),
  },
)
