import fs from 'fs'
import path from 'path'
import {colors} from '../src/legacy-theme/ts/colors'
import {fileURLToPath} from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function isObject(value: any): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function isEmpty(value: any): boolean {
  if (Array.isArray(value)) return value.length === 0
  return Object.keys(value).length === 0
}

function isShadowValue(value: unknown): boolean {
  return typeof value === 'string' && /(inset\s|)([0-9.]+(\w*)\s){1,4}(rgb[a]?\(.*\)|\w+)/.test(value)
}

function isColorValue(value: unknown): boolean {
  if (typeof value !== 'string') return false
  if (isShadowValue(value)) return false
  if (value.startsWith('#')) return true // #hex
  if (value.startsWith('rgb')) return true // rgb, rgba
  if (value.startsWith('hsl')) return true // hsl, hsla
  if (value.startsWith('var')) return true // var(--color)
  return false
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function filterObject(obj: any, predicate: (value: unknown) => boolean): any {
  if (Array.isArray(obj)) {
    return obj.filter(predicate)
  }

  return Object.entries(obj).reduce((acc: Record<string, unknown>, [key, value]) => {
    if (isObject(value)) {
      const result = filterObject(value, predicate)

      // Don't include empty objects or arrays
      if (!isEmpty(result)) {
        acc[key] = result
      }
    } else if (predicate(value)) {
      acc[key] = value
    }

    return acc
  }, {})
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function partitionColors(variables: any) {
  return {
    colors: filterObject(variables, value => isColorValue(value)),
    shadows: filterObject(variables, value => isShadowValue(value)),
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function omitScale(obj: any) {
  // This is intentionally removing `scale` from the provided object
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const {scale, ...rest} = obj
  return rest
}

const colorSchemes = Object.entries(colors).reduce((acc, [name, variables]) => {
  const {colors: schemeColors, shadows} = partitionColors(variables)
  return {
    ...acc,
    [name]: {
      colors: omitScale(schemeColors),
      shadows: omitScale(shadows),
    },
  }
}, {})

const colorSchemeFileContent = `// This file is auto-generated by precompile-color-schemes.ts
// run \`npm run build:precompile-color-schemes\` to regenerate

type Scheme = keyof typeof colors
type SchemeValue = Record<'colors' | 'shadows', Partial<typeof colors.light>>

const colors = ${JSON.stringify(colorSchemes, null, 2)}

export const colorSchemes: Record<Scheme, SchemeValue> = colors as Record<Scheme, SchemeValue>
`

fs.writeFileSync(path.join(__dirname, '../src/legacy-theme/ts/color-schemes.ts'), colorSchemeFileContent)
