const data = {
  issue: {
    labelIds: ['MDU6TGFiZWw4Mzk2MzgxMTU=', 'MDU6TGFiZWw4Mzk2MzgxMjE='],
    assigneeIds: ['MDQ6VXNlcjQxNzI2OA=='],
  },
  ref: 'main',
  collaborators: [
    {
      id: 'MDQ6VXNlcjQxNzI2OA==',
      name: 'Pavithra Kodmad',
      login: 'pksjce',
      recommended: true,
    },
    {
      id: 'MDQ6VXNlcjE0NDY1MDM=',
      name: 'Armağan',
      login: 'broccolinisoup',
      recommended: true,
    },
    {
      id: 'MDQ6VXNlcjE4NjM3NzE=',
      name: 'Siddharth Kshetrapal',
      login: 'siddharthkp',
    },
    {
      id: 'MDQ6VXNlcjIzMTM5OTg=',
      name: 'Mike Perrotti',
      login: 'mperrotti',
    },
    {
      id: 'MDQ6VXNlcjM5MDE3NjQ=',
      name: 'Josh Black',
      login: 'joshblack',
      recommended: true,
    },
    {
      id: 'MDQ6VXNlcjE4NjYxMDMw',
      name: 'Katie Langerman',
      login: 'langermank',
    },
    {
      id: 'MDQ6VXNlcjU3NTI4MA==',
      name: 'Cameron Dutro',
      login: 'camertron',
    },
  ],
  labels: [
    {
      color: 'd73a4a',
      id: 'MDU6TGFiZWw4Mzk2MzgxMTU=',
      name: 'bug',
      description: "Something isn't working",
    },
    {
      color: 'cfd3d7',
      id: 'MDU6TGFiZWw4Mzk2MzgxMTY=',
      name: 'duplicate',
      description: 'This issue or pull request already exists',
    },
    {
      color: 'a2eeef',
      id: 'MDU6TGFiZWw4Mzk2MzgxMTc=',
      name: 'enhancement',
      description: 'New feature or request',
    },
    {
      color: 'd876e3',
      id: 'MDU6TGFiZWw4Mzk2MzgxMjE=',
      name: 'futher info needed',
      description: 'Further information is requested',
    },
    {
      color: '7057ff',
      id: 'MDU6TGFiZWw4Mzk2MzgxMTk=',
      name: 'good first issue',
      description: 'Good for newcomers',
    },
    {
      color: '008672',
      id: 'MDU6TGFiZWw4Mzk2MzgxMTg=',
      name: 'up for grabs',
      description: "anyone can take on this work, it's ready to go",
    },
    {
      color: 'ffffff',
      id: 'MDU6TGFiZWw4Mzk2MzgxMjI=',
      name: 'wontfix',
      description: 'This will not be worked on',
    },
    {
      color: 'FFD2ED',
      id: 'MDU6TGFiZWw4ODkxNjUwNzU=',
      name: '💓collab',
      description: 'a vibrant hub of collaboration',
    },
    {
      color: '9eea90',
      id: 'MDU6TGFiZWw5NDAyMzcyOTU=',
      name: 'status: wip',
    },
    {
      color: 'eae658',
      id: 'MDU6TGFiZWw5NDAyMzc1NzY=',
      name: 'status: review needed',
    },
    {
      color: 'a9abe8',
      id: 'MDU6TGFiZWw5NDA1MDc5NzQ=',
      name: 'type: discussion',
    },
    {
      color: '86181d',
      id: 'MDU6TGFiZWw5NDg2NDM1MzI=',
      name: '🚧 blocked',
      description: 'Someone or something is preventing this from moving forward',
    },
    {
      color: '1d76db',
      id: 'MDU6TGFiZWwxMDI2NDE1MTYw',
      name: 'docs',
      description: 'Documentation',
    },
    {
      color: 'fcc0dc',
      id: 'MDU6TGFiZWwxMDU3MjcwNzA4',
      name: 'patch release',
      description: 'bug fixes, docs, housekeeping',
    },
    {
      color: 'ff73b4',
      id: 'MDU6TGFiZWwxMDU3MjcxMDUz',
      name: 'minor release',
      description: 'new features',
    },
    {
      color: 'e3006a',
      id: 'MDU6TGFiZWwxMDU3MjcxNDE5',
      name: 'major release',
      description: 'breaking changes',
    },
    {
      color: '107d93',
      id: 'MDU6TGFiZWwxMDU3MjczMjkz',
      name: 'deployment',
    },
    {
      color: 'd4c5f9',
      id: 'MDU6TGFiZWwxMzgyNTYyNjQ0',
      name: 'accessibility',
    },
    {
      color: '0366d6',
      id: 'MDU6TGFiZWwxNjE2MTQ5MDE2',
      name: 'dependencies',
      description: 'Pull requests that update a dependency file',
    },
    {
      color: 'e1e4e8',
      id: 'MDU6TGFiZWwxNjU3MjI0NTcw',
      name: 'fr-skip',
      description: 'Remove this from the Design Systems first responder list',
    },
    {
      color: 'fcba03',
      id: 'MDU6TGFiZWwxNzkwMDY4Mzk5',
      name: 'developer experience',
    },
    {
      color: '68f9cc',
      id: 'MDU6TGFiZWwxNzkwMDY4NDg1',
      name: 'contributor experience',
    },
    {
      color: 'a1b220',
      id: 'MDU6TGFiZWwxNzkwMDcyODY5',
      name: 'API',
    },
    {
      color: '6494f4',
      id: 'MDU6TGFiZWwxNzkxNjM5MzM1',
      name: 'new component',
    },
    {
      color: 'f48b96',
      id: 'MDU6TGFiZWwxOTg5MDAwNjk0',
      name: 'experimental',
    },
    {
      color: 'db9360',
      id: 'MDU6TGFiZWwxOTkzNTcwNzUx',
      name: 'design',
    },
    {
      color: 'F9D0C4',
      id: 'MDU6TGFiZWwyNjkzNTE0OTQw',
      name: 'coverage',
    },
    {
      color: '077CA4',
      id: 'MDU6TGFiZWwyNjkzNTE5NTc1',
      name: 'epic',
    },
    {
      color: 'F9D0C4',
      id: 'MDU6TGFiZWwyNjkzNTMwODUy',
      name: 'behaviors',
    },
    {
      color: '1d76db',
      id: 'MDU6TGFiZWwyNzkzMjYwMTgz',
      name: 'typescript',
    },
    {
      color: 'DBEDFF',
      id: 'MDU6TGFiZWwzMzA5MjY0Nzcz',
      name: 'size: sand',
    },
    {
      color: 'DBEDFF',
      id: 'MDU6TGFiZWwzMzA5MjY1MDM2',
      name: 'size: pebble',
    },
    {
      color: 'DBEDFF',
      id: 'MDU6TGFiZWwzMzA5MjY1MTc4',
      name: 'size: rock',
    },
    {
      color: 'DBEDFF',
      id: 'MDU6TGFiZWwzMzA5MjY1NTg3',
      name: 'size: boulder',
    },
    {
      color: 'ededed',
      id: 'MDU6TGFiZWwzMzE4NjA1ODgy',
      name: 'Stale',
      description: null,
    },
    {
      color: '0052CC',
      id: 'LA_kwDOB0K8ws7Oq_eD',
      name: 'react',
    },
    {
      color: 'eeeeee',
      id: 'LA_kwDOB0K8ws7O4h4u',
      name: 'skip changeset',
    },
    {
      color: 'D93F0B',
      id: 'LA_kwDOB0K8ws7WuYLd',
      name: 'do not merge',
    },
    {
      color: 'e5534b',
      id: 'LA_kwDOB0K8ws73bq-W',
      name: 'needs triage',
    },
    {
      color: 'B60205',
      id: 'LA_kwDOB0K8ws8AAAABA3IfBw',
      name: 'a11y-eng-secondary',
    },
    {
      color: 'ffffff',
      id: 'LA_kwDOB0K8ws8AAAABBfG7EQ',
      name: 'support',
      description: 'Tasks where the team is supporting and helping other teams',
    },
    {
      color: 'DDF4FF',
      id: 'LA_kwDOB0K8ws8AAAABG14Q1Q',
      name: 'component: tree view',
      description: 'Issues related to the TreeView component',
    },
    {
      color: 'DDF4FF',
      id: 'LA_kwDOB0K8ws8AAAABHLXdxw',
      name: 'component: SplitPageLayout',
      description: 'Issues related to the PageLayout and SplitPageLayout components',
    },
    {
      color: 'DDF4FF',
      id: 'LA_kwDOB0K8ws8AAAABHLXucw',
      name: 'component: nav list',
      description: 'Issues related to the NavList component',
    },
    {
      color: 'DDF4FF',
      id: 'LA_kwDOB0K8ws8AAAABHLYCfQ',
      name: 'component: button',
      description: 'Issues related to the Button component',
    },
  ],
  users: [
    {
      id: 'MDQ6VXNlcjQxNzI2OA==',
      name: 'Pavithra Kodmad',
      login: 'pksjce',
    },
    {
      id: 'MDQ6VXNlcjE5NDAyOTQ=',
      name: 'Joel Hawksley',
      login: 'joelhawksley',
    },
    {
      id: 'MDQ6VXNlcjkxMjIzNg==',
      name: 'Josep Martins',
      login: 'josepmartins',
    },
    {
      id: 'MDQ6VXNlcjE0NDY1MDM=',
      name: 'Armağan',
      login: 'broccolinisoup',
    },
    {
      id: 'MDQ6VXNlcjE4NjM3NzE=',
      name: 'Siddharth Kshetrapal',
      login: 'siddharthkp',
    },
    {
      id: 'MDQ6VXNlcjIzMTM5OTg=',
      name: 'Mike Perrotti',
      login: 'mperrotti',
    },
    {
      id: 'MDQ6VXNlcjM5MDE3NjQ=',
      name: 'Josh Black',
      login: 'joshblack',
    },
    {
      id: 'MDQ6VXNlcjE4NjYxMDMw',
      name: 'Katie Langerman',
      login: 'langermank',
    },
    {
      id: 'MDQ6VXNlcjU3NTI4MA==',
      name: 'Cameron Dutro',
      login: 'camertron',
    },
    {
      id: 'MDQ6VXNlcjg2MTY5NjI=',
      name: 'Matthew Costabile',
      login: 'mattcosta7',
    },
    {
      id: 'MDQ6VXNlcjE4Mg==',
      name: 'Matt Todd',
      login: 'mtodd',
    },
    {
      id: 'MDQ6VXNlcjIyMg==',
      name: 'Chad Humphries',
      login: 'spicycode',
    },
    {
      id: 'MDQ6VXNlcjM3OA==',
      name: 'Tim Pope',
      login: 'tpope',
    },
    {
      id: 'MDQ6VXNlcjYyMw==',
      name: 'Jonathan Hoyt',
      login: 'jonmagic',
    },
    {
      id: 'MDQ6VXNlcjgzNg==',
      name: 'Cameron Booth',
      login: 'cdb',
    },
    {
      id: 'MDQ6VXNlcjIxNjE=',
      name: 'Federico Builes',
      login: 'febuiles',
    },
    {
      id: 'MDQ6VXNlcjIyMDU=',
      name: 'Kevin Glowacz',
      login: 'kjg',
    },
    {
      id: 'MDQ6VXNlcjI0OTg=',
      name: 'Patrick Thomson',
      login: 'patrickt',
    },
    {
      id: 'MDQ6VXNlcjI2OTQ=',
      name: 'Ned Schwartz',
      login: 'theinterned',
    },
    {
      id: 'MDQ6VXNlcjI3NDU=',
      name: 'Rufo Sanchez',
      login: 'rufo',
    },
    {
      id: 'MDQ6VXNlcjMzNDA=',
      name: 'Matt Gauger',
      login: 'mathias',
    },
    {
      id: 'MDQ6VXNlcjMzNDE=',
      name: 'Abraham Williams',
      login: 'abraham',
    },
    {
      id: 'MDQ6VXNlcjMzNjU=',
      name: 'Ben Sherman',
      login: 'bensherman',
    },
    {
      id: 'MDQ6VXNlcjM2MzU=',
      name: 'Karl Krukow',
      login: 'krukow',
    },
    {
      id: 'MDQ6VXNlcjM5OTI=',
      name: 'Manuel Muñoz Solera',
      login: 'mamuso',
    },
    {
      id: 'MDQ6VXNlcjM5OTk=',
      name: 'Nathan Witmer',
      login: 'zerowidth',
    },
    {
      id: 'MDQ6VXNlcjQyODI=',
      name: 'Jeremy Israelsen',
      login: 'jisraelsen',
    },
    {
      id: 'MDQ6VXNlcjU0Nzg=',
      name: 'Jared Fine',
      login: 'jfine',
    },
    {
      id: 'MDQ6VXNlcjcwNzQ=',
      name: 'Greg Hurrell',
      login: 'wincent',
    },
    {
      id: 'MDQ6VXNlcjEwMTg2',
      name: 'Luke Francl',
      login: 'look',
    },
    {
      id: 'MDQ6VXNlcjEwODM5',
      name: 'Kevin Stevens',
      login: 'KevDog',
    },
    {
      id: 'MDQ6VXNlcjExMDUw',
      name: 'John Northrup',
      login: 'northrup',
    },
    {
      id: 'MDQ6VXNlcjExNDQz',
      name: 'Jonathan Wallace',
      login: 'wallace',
    },
    {
      id: 'MDQ6VXNlcjExOTIy',
      name: 'Jens Hilligsøe',
      login: 'hilli',
    },
    {
      id: 'MDQ6VXNlcjE3NTY1',
      name: 'Ash Wilson',
      login: 'smashwilson',
    },
    {
      id: 'MDQ6VXNlcjE3NzI1',
      name: 'Mike Griffin',
      login: 'mgriffin',
    },
    {
      id: 'MDQ6VXNlcjE3Nzcw',
      name: 'Phill MV',
      login: 'phillmv',
    },
    {
      id: 'MDQ6VXNlcjE4NjQz',
      name: 'Sho Mizutani',
      login: 'lowply',
    },
    {
      id: 'MDQ6VXNlcjE4NjQ1',
      name: 'Max Prokopiev',
      login: 'maxprokopiev',
    },
    {
      id: 'MDQ6VXNlcjE4ODQ4',
      name: 'Julian Møller Ellehauge',
      login: 'jumoel',
    },
    {
      id: 'MDQ6VXNlcjIwMTU4',
      name: 'Matt Burke',
      login: 'spraints',
    },
    {
      id: 'MDQ6VXNlcjIwMTY1',
      name: 'Philip Harrison',
      login: 'feelepxyz',
    },
    {
      id: 'MDQ6VXNlcjIxMTk1',
      name: 'Jonathan Fuchs',
      login: 'jfuchs',
    },
    {
      id: 'MDQ6VXNlcjIxMjUw',
      name: 'Chris Bloom',
      login: 'chrisbloom7',
    },
    {
      id: 'MDQ6VXNlcjIyMzQ4',
      name: 'Patrick Veverka',
      login: 'veverkap',
    },
    {
      id: 'MDQ6VXNlcjIyMzk0',
      name: 'Paul Smith',
      login: 'paulcsmith',
    },
    {
      id: 'MDQ6VXNlcjI1NDk5',
      name: 'Ramon Bispo',
      login: 'RamonPage',
    },
    {
      id: 'MDQ6VXNlcjI1NTA2',
      name: 'Bryan Dragon',
      login: 'bdragon',
    },
    {
      id: 'MDQ6VXNlcjMzNzUw',
      name: 'Lindsey Bieda',
      login: 'LindseyB',
    },
    {
      id: 'MDQ6VXNlcjMzOTIx',
      name: 'Jeff Hunter',
      login: 'jeffreyhunter77',
    },
    {
      id: 'MDQ6VXNlcjM0MTYz',
      name: 'George Drummond',
      login: 'georgedrummond',
    },
    {
      id: 'MDQ6VXNlcjM2NjA3',
      name: 'Gar',
      login: 'wraithgar',
    },
    {
      id: 'MDQ6VXNlcjM3MDQ5',
      name: 'Will Fitzgerald',
      login: 'willf',
    },
    {
      id: 'MDQ6VXNlcjM4OTI0',
      name: 'Ivan Žužak',
      login: 'izuzak',
    },
    {
      id: 'MDQ6VXNlcjM5OTky',
      name: 'Gregor Martynus',
      login: 'gr2m',
    },
    {
      id: 'MDQ6VXNlcjQxMDMw',
      name: 'Craig Steinberger',
      login: 'cjs',
    },
    {
      id: 'MDQ6VXNlcjQ1MDIw',
      name: 'Cody Soyland',
      login: 'codysoyland',
    },
    {
      id: 'MDQ6VXNlcjQ2MDE3',
      name: 'Chris Horton',
      login: 'hortoncd',
    },
    {
      id: 'MDQ6VXNlcjQ3NTU0',
      name: 'Ben Sheldon [he/him]',
      login: 'bensheldon',
    },
    {
      id: 'MDQ6VXNlcjUxOTI1',
      name: 'Brannon Jones',
      login: 'brannon',
    },
    {
      id: 'MDQ6VXNlcjU0MDA2',
      name: 'Shane Bauer',
      login: 'sbauer',
    },
    {
      id: 'MDQ6VXNlcjU0MDEy',
      name: 'Jon Rohan',
      login: 'jonrohan',
    },
    {
      id: 'MDQ6VXNlcjU1OTcw',
      name: 'Kevin Dangoor',
      login: 'dangoor',
    },
    {
      id: 'MDQ6VXNlcjU2NzUz',
      name: 'Eric Sorenson',
      login: 'ahpook',
    },
    {
      id: 'MDQ6VXNlcjY1MDU3',
      name: 'James Dennes',
      login: 'jdennes',
    },
    {
      id: 'MDQ6VXNlcjY4MTgz',
      name: 'Daniel Schauenberg',
      login: 'mrtazz',
    },
    {
      id: 'MDQ6VXNlcjcwNDky',
      name: 'Cornelius Riemenschneider',
      login: 'criemen',
    },
    {
      id: 'MDQ6VXNlcjcwNzQx',
      name: 'Stefan Haubold',
      login: 'Soph',
    },
    {
      id: 'MDQ6VXNlcjcyMDY2',
      name: 'Dominik Bamberger',
      login: 'b4mboo',
    },
    {
      id: 'MDQ6VXNlcjc0NTk4',
      name: 'Zack Fernandes',
      login: 'zackfern',
    },
    {
      id: 'MDQ6VXNlcjc3MTc0',
      name: 'Matt Rogers',
      login: 'mattr-',
    },
    {
      id: 'MDQ6VXNlcjc5OTk1',
      name: 'Garrett Bjerkhoel',
      login: 'dewski',
    },
    {
      id: 'MDQ6VXNlcjkxMjEz',
      name: 'Nathan Fritz',
      login: 'fritzy',
    },
    {
      id: 'MDQ6VXNlcjEwMzM2MA==',
      name: 'Patrick Toomey',
      login: 'ptoomey3',
    },
    {
      id: 'MDQ6VXNlcjEwODM4MA==',
      name: 'Jaana Dogan',
      login: 'rakyll',
    },
    {
      id: 'MDQ6VXNlcjExMDY4Mw==',
      name: 'Christina Warren',
      login: 'filmgirl',
    },
    {
      id: 'MDQ6VXNlcjExMzE1OA==',
      name: 'Shaun Kirk Wong',
      login: 'skw',
    },
    {
      id: 'MDQ6VXNlcjExNDQxNw==',
      name: 'Dan Rigby',
      login: 'DanRigby',
    },
    {
      id: 'MDQ6VXNlcjExNTQwOQ==',
      name: 'Seth Juarez',
      login: 'sethjuarez',
    },
    {
      id: 'MDQ6VXNlcjExNjEzNA==',
      name: 'Tim Rogers',
      login: 'timrogers',
    },
    {
      id: 'MDQ6VXNlcjExODI2Ng==',
      name: 'Keith Cirkel',
      login: 'keithamus',
    },
    {
      id: 'MDQ6VXNlcjExODU0OQ==',
      name: 'Sven Pfleiderer',
      login: 'pfleidi',
    },
    {
      id: 'MDQ6VXNlcjEyMTMyMg==',
      name: 'Lee Reilly',
      login: 'leereilly',
    },
    {
      id: 'MDQ6VXNlcjEyMTUzOQ==',
      name: 'Patrick Dinger',
      login: 'paxos',
    },
    {
      id: 'MDQ6VXNlcjEyMzMyNQ==',
      name: 'Robson Júnior',
      login: 'bsao',
    },
    {
      id: 'MDQ6VXNlcjEyMzU3NA==',
      name: 'Erwin Kroon',
      login: 'ekroon',
    },
    {
      id: 'MDQ6VXNlcjEyNTA1NQ==',
      name: 'Scott Densmore',
      login: 'scottdensmore',
    },
    {
      id: 'MDQ6VXNlcjEyNTcwMQ==',
      name: 'Alvaro Muñoz',
      login: 'pwntester',
    },
    {
      id: 'MDQ6VXNlcjEyNjczMQ==',
      name: 'AJ Schuster',
      login: 'schustafa',
    },
    {
      id: 'MDQ6VXNlcjEyNzc5MA==',
      name: 'Johannes Schindelin',
      login: 'dscho',
    },
    {
      id: 'MDQ6VXNlcjEzMzM1OQ==',
      name: 'Christopher Kintner',
      login: 'kintner',
    },
    {
      id: 'MDQ6VXNlcjEzNDUyNw==',
      name: 'Ole Friis Østergaard',
      login: 'olefriis',
    },
    {
      id: 'MDQ6VXNlcjEzNTEzOQ==',
      name: 'Miguel Ángel Pastor Olivar',
      login: 'migue',
    },
    {
      id: 'MDQ6VXNlcjEzOTgxOQ==',
      name: 'Nick Floyd',
      login: 'nickfloyd',
    },
    {
      id: 'MDQ6VXNlcjE0NzAyNw==',
      name: 'Andrew Mildahl',
      login: 'amildahl',
    },
    {
      id: 'MDQ6VXNlcjE1MDI4Mg==',
      name: 'Asier',
      login: 'asiermartinez',
    },
    {
      id: 'MDQ6VXNlcjE1MTA0NQ==',
      name: 'Michael Renner',
      login: 'terrorobe',
    },
    {
      id: 'MDQ6VXNlcjE1ODMwNg==',
      name: 'Nick Rolfe',
      login: 'nickrolfe',
    },
    {
      id: 'MDQ6VXNlcjE1OTkyOQ==',
      name: 'Haldun Bayhantopcu',
      login: 'haldun',
    },
    {
      id: 'MDQ6VXNlcjE2Nzc1OQ==',
      name: 'Zach Steindler',
      login: 'steiza',
    },
    {
      id: 'MDQ6VXNlcjE3MTIxNQ==',
      name: 'Jose Cortinas',
      login: 'jacortinas',
    },
    {
      id: 'MDQ6VXNlcjE3NTYzOA==',
      name: 'Daniel Guillan',
      login: 'danielguillan',
    },
    {
      id: 'MDQ6VXNlcjE3NjgxOA==',
      name: 'Peter Stöckli',
      login: 'p-',
    },
    {
      id: 'MDQ6VXNlcjE3ODEwNg==',
      name: 'Mikkel Mondrup Kristensen',
      login: 'monrad',
    },
    {
      id: 'MDQ6VXNlcjE4MDk1Ng==',
      name: 'Russell Horton',
      login: 'mrjf',
    },
    {
      id: 'MDQ6VXNlcjE4NTEyMg==',
      name: 'Chris Patterson',
      login: 'chrispat',
    },
    {
      id: 'MDQ6VXNlcjE4NjA4Nw==',
      name: 'Fran Casas',
      login: 'franciscoj',
    },
    {
      id: 'MDQ6VXNlcjE4NjQ1MQ==',
      name: "Salvatore D'Agostino",
      login: 'iToto',
    },
    {
      id: 'MDQ6VXNlcjE5MDA1Ng==',
      name: 'Shaikhul Islam',
      login: 'shaikhul',
    },
    {
      id: 'MDQ6VXNlcjE5MzkxNg==',
      name: 'Tyler Johnston',
      login: 'tylerjohnst',
    },
  ],
  branches: [
    {id: 'main', name: 'main', trailingInfo: 'Default'},
    {id: 'next-major', name: 'next-major'},
    {id: 'changeset-release/main', name: 'changeset-release/main'},
    {id: 'changeset-release/next-major', name: 'changeset-release/next-major'},
    {id: 'selectpanel-2', name: 'selectpanel-2'},
    {id: 'bs/actionlist-heading', name: 'bs/actionlist-heading'},
    {id: 'refactor/support-alt-names', name: 'refactor/support-alt-names'},
    {id: 'fix/update-action-list', name: 'fix/update-action-list'},
    {id: 'dependabot/markdownlint-github-0.4.1', name: 'dependabot/markdownlint-github-0.4.1'},
  ],
  tags: [
    {id: 'v35.31.0', name: 'v35.31.0', trailingInfo: 'Latest'},
    {id: 'v35.30.0', name: 'v35.30.0'},
    {id: 'v35.29.0', name: 'v35.29.0'},
    {id: 'v35.28.0', name: 'v35.28.0'},
    {id: 'v35.27.1', name: 'v35.27.1'},
    {id: 'v35.27.0', name: 'v35.27.0'},
    {id: 'v35.26.1', name: 'v35.26.1'},
    {id: 'v35.26.0', name: 'v35.26.0'},
    {id: 'v35.0.0', name: 'v35.0.0'},
    {id: 'v34.0.0', name: 'v34.0.0'},
  ],
}

export default data
