#!/bin/bash

set -e

# Clean up
npm run clean

# Bundle
npx rollup -c --bundleConfigAsCjs

# Type check
npx tsc --project tsconfig.build.json

# Copy type declarations
npx copyfiles -u 1 "./lib/**/*.d.ts" ./lib-esm

# Copy css
npx copyfiles --flat ./lib/components.css ./css

# Build components.json file for documentation
npx ts-node script/components-json/build
