#!/bin/bash

set -e

# Clean up
npm run clean

# Bundle
npx rollup -c --bundleConfigAsCjs

# Type check
npx tsc --project tsconfig.build.json

# Copy css
npx copyfiles --flat ./lib/components.css ./css
