#!/bin/bash

set -e

# Clean up
npm run clean

# Bundle
npx cross-env NODE_ENV=production rollup -c

# Type check
npx tsc --project tsconfig.build.json

# Copy type declarations
npx copyfiles -u 1 "./lib/**/*.d.ts" ./lib-esm
