#!/bin/bash

# Install dependencies
npm install

# Build
npm run build

# Install docs dependencies
pushd docs
npm install --legacy-peer-deps
popd

# Install examples dependencies
pushd examples/nextjs
npm install --legacy-peer-deps
popd
