#!/bin/bash

set -x

PLAYWRIGHT_VERSION=$(npm --json list @playwright/test | jq --raw-output '.dependencies["@playwright/test"].version')

docker run --rm \
  --network host \
  -v $(pwd):/workspace \
  -w /workspace \
  -it "mcr.microsoft.com/playwright:v$PLAYWRIGHT_VERSION-jammy" \
  /bin/bash -c "npm install && STORYBOOK_URL=http://host.docker.internal:6006 npx playwright test $@"
