import React from 'react'
import TabNav from './TabNav'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(TabNav, 'https://www.figma.com/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=24375-94677&m=dev', {
  props: {
    children: figma.children('TabNav.Link'),
    trailingAction: figma.boolean('trailingAction?', {
      true: figma.children('Action'),
      false: undefined,
    }),
  },
  example: ({children, trailingAction}) => (
    <TabNav>
      {children}
      {trailingAction}
    </TabNav>
  ),
})

figma.connect(
  TabNav.Link,
  'https://www.figma.com/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=18247-69223&t=hRAVLxy8fN4FzpK2-4',
  {
    props: {
      selected: figma.enum('state', {selected: true}),
      label: figma.string('label'),
      counter: figma.boolean('counter?', {
        true: figma.children('CounterLabel'),
        false: undefined,
      }),
      leadingVisual: figma.boolean('leadingVisual?', {
        true: figma.children('leadingVisual'),
        false: undefined,
      }),
    },
    example: ({label, selected, counter, leadingVisual}) => (
      <TabNav.Link selected={selected}>
        {leadingVisual}
        {label}
        {counter}
      </TabNav.Link>
    ),
  },
)
