import React from 'react'
import {Avatar} from '../../src'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  'https://www.figma.com/file/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?type=design&node-id=3805-11&mode=design&t=n5UtEmPJTCzDEJKK-4',
  {
    props: {
      size: figma.enum('size', {
        '16px': 16,
        '20px': 20,
        '24px': 24,
        '28px': 28,
        '32px': 32,
        '40px': 40,
        '48px': 48,
        '64px': 64,
      }),
      square: figma.boolean('square'),
    },
    example: ({size, square}) => <Avatar src="/path/to/file/mona.png" size={size} square={square} />,
  },
)
