/* eslint-disable github/unescaped-html-literal */

'use strict'

/**
 * @type {import('jest').Config}
 */
module.exports = {
  testEnvironment: 'jsdom',
  collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}', '!src/stories/**', '!**/*.stories.{js,jsx,ts,tsx}'],
  moduleNameMapper: {
    '\\.css$': 'jest-css-modules',
  },
  setupFiles: ['<rootDir>/src/utils/test-helpers.tsx'],
  setupFilesAfterEnv: ['<rootDir>/src/utils/test-matchers.tsx', '<rootDir>/src/utils/test-deprecations.tsx'],
  testMatch: ['<rootDir>/**/*.test.[jt]s?(x)', '!**/*.types.test.[jt]s?(x)'],
  modulePathIgnorePatterns: [
    '<rootDir>/src/ActionBar/',
    '<rootDir>/src/ActionList/',
    '<rootDir>/src/AnchoredOverlay/',
    '<rootDir>/src/Banner/',
    '<rootDir>/src/Blankslate/',
    '<rootDir>/src/BranchName/',
    '<rootDir>/src/Breadcrumbs/',
    '<rootDir>/src/ButtonGroup/',
    '<rootDir>/src/CheckboxGroup/',
    '<rootDir>/src/CircleBadge/',
    '<rootDir>/src/CircleOcticon/',
    '<rootDir>/src/DataTable/',
    '<rootDir>/src/FeatureFlags/',
    '<rootDir>/src/FormControl/__tests__/FormControl.Validation.test.tsx',
    '<rootDir>/src/NavList/',
    '<rootDir>/src/Octicon/',
    '<rootDir>/src/Pagehead/',
    '<rootDir>/src/Pagination/',
    '<rootDir>/src/ProgressBar/',
    '<rootDir>/src/Radio/',
    '<rootDir>/src/RadioGroup/',
    '<rootDir>/src/RelativeTime/',
    '<rootDir>/src/ScrollableRegion/',
    '<rootDir>/src/Select/',
    '<rootDir>/src/Skeleton/',
    '<rootDir>/src/Spinner/',
    '<rootDir>/src/Stack/',
    '<rootDir>/src/StateLabel/',
    '<rootDir>/src/SubNav/',
    '<rootDir>/src/TabNav/',
    '<rootDir>/src/TextInputWithTokens/',
    '<rootDir>/src/Textarea/',
    '<rootDir>/src/Timeline/',
    '<rootDir>/src/ToggleSwitch/',
    '<rootDir>/src/Tooltip/',
    '<rootDir>/src/TooltipV2/',
    '<rootDir>/src/Truncate/',
    '<rootDir>/src/UnderlineNav/',
    '<rootDir>/src/__tests__/BaseStyles.test.tsx',
    '<rootDir>/src/__tests__/Caret.test.tsx',
    '<rootDir>/src/__tests__/CheckboxOrRadioGroup.test.tsx',
    '<rootDir>/src/__tests__/exports.test.ts',
    '<rootDir>/src/__tests__/filterObject.test.ts',
    '<rootDir>/src/__tests__/SideNav.test.tsx',
    '<rootDir>/src/__tests__/SubNavLink.test.tsx',
    '<rootDir>/src/__tests__/theme.test.ts',
    '<rootDir>/src/__tests__/themeGet.test.ts',
    '<rootDir>/src/__tests__/ThemeProvider.test.tsx',
    '<rootDir>/src/__tests__/useSafeTimeout.test.ts',
    '<rootDir>/src/experimental/Skeleton',
    '<rootDir>/src/hooks/',
    '<rootDir>/src/live-region/',
    '<rootDir>/src/utils/__tests__/invariant.test.ts',
    '<rootDir>/src/utils/__tests__/warning.test.ts',
  ],
  transformIgnorePatterns: ['node_modules/(?!@github/[a-z-]+-element|@lit-labs/react|@oddbird/popover-polyfill)'],
}
