import react from '@vitejs/plugin-react'
import {defineConfig} from 'vitest/config'
import postcssPresetPrimer from 'postcss-preset-primer'

export default defineConfig({
  css: {
    modules: {
      generateScopedName: 'prc-[folder]-[local]-[hash:base64:5]',
    },
    postcss: {
      plugins: [postcssPresetPrimer()],
    },
  },
  plugins: [react()],
  define: {
    __DEV__: true,
    'process.env.CI': JSON.stringify(process.env.CI),
  },
  test: {
    name: '@primer/react',
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      '**/lib-esm/**',
      '**/lib/**',
      '**/generated/**',
      '**/*.figma.tsx',
      '**/*.types.test.tsx',
    ],
    include: [
      'src/ActionBar/**/*.test.?(c|m)[jt]s?(x)',
      'src/ActionList/**/*.test.?(c|m)[jt]s?(x)',
      'src/AnchoredOverlay/**/*.test.?(c|m)[jt]s?(x)',
      'src/Autocomplete/**/*.test.?(c|m)[jt]s?(x)',
      'src/Avatar/**/*.test.?(c|m)[jt]s?(x)',
      'src/AvatarStack/**/*.test.?(c|m)[jt]s?(x)',
      'src/Banner/**/*.test.?(c|m)[jt]s?(x)',
      'src/Blankslate/**/*.test.?(c|m)[jt]s?(x)',
      'src/Box/**/*.test.?(c|m)[jt]s?(x)',
      'src/BranchName/**/*.test.?(c|m)[jt]s?(x)',
      'src/Breadcrumbs/**/*.test.?(c|m)[jt]s?(x)',
      'src/ButtonGroup/**/*.test.?(c|m)[jt]s?(x)',
      'src/Checkbox/**/*.test.?(c|m)[jt]s?(x)',
      'src/CheckboxGroup/**/*.test.?(c|m)[jt]s?(x)',
      'src/CircleBadge/**/*.test.?(c|m)[jt]s?(x)',
      'src/CircleOcticon/**/*.test.?(c|m)[jt]s?(x)',
      'src/DataTable/**/*.test.?(c|m)[jt]s?(x)',
      'src/Dialog/**/*.test.?(c|m)[jt]s?(x)',
      'src/DialogV1/**/*.test.?(c|m)[jt]s?(x)',
      'src/FeatureFlags/**/*.test.?(c|m)[jt]s?(x)',
      'src/Flash/**/*.test.?(c|m)[jt]s?(x)',
      'src/FormControl/**/*.test.?(c|m)[jt]s?(x)',
      'src/Heading/**/*.test.?(c|m)[jt]s?(x)',
      'src/InlineMessage/**/*.test.?(c|m)[jt]s?(x)',
      'src/Hidden/**/*.test.?(c|m)[jt]s?(x)',
      'src/Label/**/*.test.?(c|m)[jt]s?(x)',
      'src/NavList/**/*.test.?(c|m)[jt]s?(x)',
      'src/Octicon/**/*.test.?(c|m)[jt]s?(x)',
      'src/Overlay/**/*.test.?(c|m)[jt]s?(x)',
      'src/PageHeader/**/*.test.?(c|m)[jt]s?(x)',
      'src/PageLayout/**/*.test.?(c|m)[jt]s?(x)',
      'src/Pagehead/**/*.test.?(c|m)[jt]s?(x)',
      'src/Pagination/**/*.test.?(c|m)[jt]s?(x)',
      'src/ProgressBar/**/*.test.?(c|m)[jt]s?(x)',
      'src/Radio/**/*.test.?(c|m)[jt]s?(x)',
      'src/RadioGroup/**/*.test.?(c|m)[jt]s?(x)',
      'src/RelativeTime/**/*.test.?(c|m)[jt]s?(x)',
      'src/ScrollableRegion/**/*.test.?(c|m)[jt]s?(x)',
      'src/SegmentedControl/**/*.test.?(c|m)[jt]s?(x)',
      'src/Select/**/*.test.?(c|m)[jt]s?(x)',
      'src/Skeleton/**/*.test.?(c|m)[jt]s?(x)',
      'src/SkeletonAvatar/**/*.test.?(c|m)[jt]s?(x)',
      'src/SkeletonText/**/*.test.?(c|m)[jt]s?(x)',
      'src/Spinner/**/*.test.?(c|m)[jt]s?(x)',
      'src/SplitPageLayout/**/*.test.?(c|m)[jt]s?(x)',
      'src/Stack/**/*.test.?(c|m)[jt]s?(x)',
      'src/StateLabel/**/*.test.?(c|m)[jt]s?(x)',
      'src/SubNav/**/*.test.?(c|m)[jt]s?(x)',
      'src/TabNav/**/*.test.?(c|m)[jt]s?(x)',
      'src/TextInputWithTokens/**/*.test.?(c|m)[jt]s?(x)',
      'src/Textarea/**/*.test.?(c|m)[jt]s?(x)',
      'src/Timeline/**/*.test.?(c|m)[jt]s?(x)',
      'src/ToggleSwitch/**/*.test.?(c|m)[jt]s?(x)',
      'src/Tooltip/**/*.test.?(c|m)[jt]s?(x)',
      'src/TooltipV2/**/*.test.?(c|m)[jt]s?(x)',
      'src/TreeView/**/*.test.?(c|m)[jt]s?(x)',
      'src/Truncate/**/*.test.?(c|m)[jt]s?(x)',
      'src/UnderlineNav/**/*.test.?(c|m)[jt]s?(x)',
      'src/__tests__/BaseStyles.test.tsx',
      'src/__tests__/Caret.test.tsx',
      'src/__tests__/CheckboxOrRadioGroup.test.tsx',
      'src/__tests__/deprecated/ActionMenu.test.tsx',
      'src/__tests__/SideNav.test.tsx',
      'src/__tests__/SubNavLink.test.tsx',
      'src/__tests__/ThemeProvider.test.tsx',
      'src/__tests__/filterObject.test.ts',
      'src/__tests__/theme.test.ts',
      'src/__tests__/themeGet.test.ts',
      'src/deprecated/**/*.test.?(c|m)[jt]s?(x)',
      'src/hooks/**/*.test.?(c|m)[jt]s?(x)',
      'src/internal/utils/**/*.test.?(c|m)[jt]s?(x)',
      'src/live-region/**/*.test.?(c|m)[jt]s?(x)',
      'src/utils/**/*.test.?(c|m)[jt]s?(x)',
    ],
    setupFiles: ['config/vitest/setup.ts', 'config/vitest/browser/setup.ts'],
    css: {
      include: [/.+/],
    },
    browser: {
      provider: 'playwright',
      enabled: true,
      headless: process.env.DEBUG_BROWSER_TESTS === 'true' ? false : true,
      instances: [
        {
          browser: 'chromium',
        },
      ],
      screenshotFailures: false,
    },
  },
})
