import React from 'react'
import {AvatarStack} from '../../src'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AvatarStack,
  'https://www.figma.com/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=3805-24&t=eMfIgDUcIkVQzl79-4',
  {
    props: {
      children: figma.children('*'),
    },
    example: ({children}) => <AvatarStack>{children}</AvatarStack>,
  },
)
