import './global.css'
import {cookies} from 'next/headers'
import {BaseStyles, ThemeProvider} from '@primer/react'
import {StyledComponentsRegistry} from './registry'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  const cookieStore = cookies()
  const colorPreferenceCookie = cookieStore.get('color-preference')
  const preference = colorPreferenceCookie ? colorPreferenceCookie.value : 'auto'

  return (
    // Note: the focus-visible polyfill adds additional attributes to `html`
    // that cause hydration mismatch errors
    <html
      lang="en"
      suppressHydrationWarning
      data-color-mode={preference}
      data-light-theme="light"
      data-dark-theme="dark"
    >
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider colorMode="night">
            <BaseStyles>{children}</BaseStyles>
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
