import './global.css'
import {cookies} from 'next/headers'
import {BaseStyles, ThemeProvider} from '@primer/styled-react'
import {StyledComponentsRegistry} from './registry'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({children}: {children: React.ReactNode}) {
  const cookieStore = await cookies()
  const colorPreferenceCookie = cookieStore.get('color-preference')
  const colorMode = getColorMode(colorPreferenceCookie?.value)

  return (
    // Note: the focus-visible polyfill adds additional attributes to `html`
    // that cause hydration mismatch errors
    <html
      lang="en"
      suppressHydrationWarning
      data-color-mode={colorMode}
      data-light-theme="light"
      data-dark-theme="dark"
    >
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider colorMode={colorMode}>
            <BaseStyles>{children}</BaseStyles>
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}

function getColorMode(preference?: string): 'light' | 'dark' | 'auto' {
  if (preference === 'light' || preference === 'dark') {
    return preference
  }
  return 'auto'
}
