import React from "react"
import { Textarea } from "./Textarea"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Textarea,
  "https://www.figma.com/design/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=30948-151237&t=39jWyeflbJqVh77d-4",
  {
    props: {
      contrast: figma.boolean("contrast"),
      label: figma.boolean("label?"),
      text: figma.string("text"),
      caption: figma.boolean("caption?"),
      state: figma.enum("state", {
        default: "default",
        focus: "focus",
        disabled: "disabled",
      }),
      validation: figma.enum("validation", {
        none: "none",
        invalid: "invalid",
        success: "success",
      }),
      texttype: figma.enum("text type", {
        Value: "value",
        Placeholder: "placeholder",
      }),
    },
    example: (props) => <Textarea />,
  },
)
