// Code generated by script/figma-connect-icons.ts. DO NOT EDIT.

import React from 'react'
import figma from '@figma/code-connect'
import {
  InfinityIcon,
  FileBinaryIcon,
  PackageDependenciesIcon,
  ArrowUpLeftIcon,
  RubyIcon,
  PackageDependentsIcon,
  DiffRenamedIcon,
  HourglassIcon,
  MoveToStartIcon,
  TabIcon,
  GitPullRequestIcon,
  AccessibilityInsetIcon,
  GoalIcon,
  ZoomOutIcon,
  LogoGithubIcon,
  FileMediaIcon,
  ChevronRightIcon,
  FiscalHostIcon,
  DiffRemovedIcon,
  FileMovedIcon,
  MoveToBottomIcon,
  XIcon,
  PaperAirplaneIcon,
  HashIcon,
  UndoIcon,
  CheckCircleFillIcon,
  UnlinkIcon,
  EllipsisIcon,
  VideoIcon,
  KebabHorizontalIcon,
  ArrowBothIcon,
  ServerIcon,
  StopIcon,
  SquareFillIcon,
  SmileyIcon,
  CreditCardIcon,
  PivotColumnIcon,
  HeartIcon,
  ListOrderedIcon,
  ItalicIcon,
  CircleIcon,
  CodeOfConductIcon,
  BellFillIcon,
  TelescopeIcon,
  ArrowUpIcon,
  QuestionIcon,
  ScreenFullIcon,
  ShieldCheckIcon,
  ArrowLeftIcon,
  SyncIcon,
  VersionsIcon,
  IdBadgeIcon,
  IterationsIcon,
  AlertFillIcon,
  RowsIcon,
  GitMergeIcon,
  DownloadIcon,
  FileIcon,
  SlidersIcon,
  RocketIcon,
  ChevronLeftIcon,
  HomeFillIcon,
  GrabberIcon,
  ZoomInIcon,
  StarFillIcon,
  RedoIcon,
  FileRemovedIcon,
  ChevronDownIcon,
  SidebarCollapseIcon,
  SkipFillIcon,
  ZapIcon,
  SearchIcon,
  MarkGithubIcon,
  PeopleIcon,
  HeadingIcon,
  DiamondIcon,
  ArrowSwitchIcon,
  PinSlashIcon,
  LocationIcon,
  ArrowUpRightIcon,
  SparkleFillIcon,
  TrashIcon,
  FileDirectoryOpenFillIcon,
  ShareAndroidIcon,
  DuplicateIcon,
  FoldUpIcon,
  GitCommitIcon,
  BellIcon,
  FileCodeIcon,
  BookmarkSlashIcon,
  BellSlashIcon,
  MegaphoneIcon,
  CommandPaletteIcon,
  TriangleRightIcon,
  ProjectRoadmapIcon,
  NumberIcon,
  PaperclipIcon,
  TriangleUpIcon,
  ChevronUpIcon,
  FileSubmoduleIcon,
  MortarBoardIcon,
  NoteIcon,
  CodescanIcon,
  WorkflowIcon,
  CommentIcon,
  ArrowRightIcon,
  SunIcon,
  DiffModifiedIcon,
  HorizontalRuleIcon,
  ContainerIcon,
  EyeIcon,
  CloudOfflineIcon,
  UnlockIcon,
  ShieldXIcon,
  CrossReferenceIcon,
  BookmarkFillIcon,
  ThumbsdownIcon,
  DeviceMobileIcon,
  BookmarkSlashFillIcon,
  DesktopDownloadIcon,
  CodeReviewIcon,
  FoldDownIcon,
  CloudIcon,
  MirrorIcon,
  MarkdownIcon,
  SortAscIcon,
  BrowserIcon,
  SidebarExpandIcon,
  ColumnsIcon,
  SquirrelIcon,
  MoveToTopIcon,
  UnverifiedIcon,
  PersonIcon,
  LogIcon,
  TypographyIcon,
  FeedMergedIcon,
  DeviceCameraVideoIcon,
  BoldIcon,
  ToolsIcon,
  FileDiffIcon,
  CpuIcon,
  NorthStarIcon,
  HistoryIcon,
  FoldIcon,
  MentionIcon,
  DotIcon,
  LockIcon,
  QuoteIcon,
  ScreenNormalIcon,
  BroadcastIcon,
  RepoPushIcon,
  HubotIcon,
  ShieldLockIcon,
  GitBranchIcon,
  MuteIcon,
  DependabotIcon,
  DiffAddedIcon,
  FilterIcon,
  PulseIcon,
  TabExternalIcon,
  RelFilePathIcon,
  ArchiveIcon,
  UnmuteIcon,
  SkipIcon,
  FileZipIcon,
  GitPullRequestClosedIcon,
  RepoLockedIcon,
  CircleSlashIcon,
  FileAddedIcon,
  ReplyIcon,
  InboxIcon,
  PlugIcon,
  StrikethroughIcon,
  UnfoldIcon,
  TriangleLeftIcon,
  MultiSelectIcon,
  RssIcon,
  GiftIcon,
  DatabaseIcon,
  SingleSelectIcon,
  FeedRocketIcon,
  WebhookIcon,
  SortDescIcon,
  ArrowDownRightIcon,
  SquareIcon,
  SponsorTiersIcon,
  KeyAsteriskIcon,
  ArrowDownIcon,
  SignOutIcon,
  PaintbrushIcon,
  CacheIcon,
  MoveToEndIcon,
  ReportIcon,
  PersonFillIcon,
  ArrowDownLeftIcon,
  ShieldSlashIcon,
  NoEntryFillIcon,
  BeakerIcon,
  FeedDiscussionIcon,
  NoEntryIcon,
  ShareIcon,
  CopyIcon,
  LogoGistIcon,
  UnreadIcon,
  TasklistIcon,
  FeedHeartIcon,
  IssueReopenedIcon,
  GitMergeQueueIcon,
  FeedPersonIcon,
  FeedRepoIcon,
  IssueDraftIcon,
  MoonIcon,
  AccessibilityIcon,
  AppsIcon,
  LinkIcon,
  PlayIcon,
  RepoForkedIcon,
  TerminalIcon,
  DiffIgnoredIcon,
  BlockedIcon,
  CodescanCheckmarkIcon,
  InfoIcon,
  GitPullRequestDraftIcon,
  RepoTemplateIcon,
  SignInIcon,
  FeedStarIcon,
  DeviceDesktopIcon,
  BugIcon,
  LinkExternalIcon,
  GitCompareIcon,
  FeedTagIcon,
  FeedForkedIcon,
  BriefcaseIcon,
  KeyIcon,
  MailIcon,
  FeedTrophyIcon,
  PersonAddIcon,
  RepoDeletedIcon,
  MeterIcon,
  StopwatchIcon,
  ProjectSymlinkIcon,
  TelescopeFillIcon,
  UploadIcon,
  XCircleFillIcon,
  TableIcon,
  StarIcon,
  AlertIcon,
  TagIcon,
  GearIcon,
  ImageIcon,
  ClockIcon,
  BookIcon,
  ProjectIcon,
  GraphIcon,
  CalendarIcon,
  GlobeIcon,
  ClockFillIcon,
  CheckboxIcon,
  RepoIcon,
  ThreeBarsIcon,
  VerifiedIcon,
  ReadIcon,
  FileDirectoryIcon,
  CodeIcon,
  HomeIcon,
  CodespacesIcon,
  BookmarkIcon,
  MilestoneIcon,
  DeviceCameraIcon,
  ChecklistIcon,
  PencilIcon,
  CheckCircleIcon,
  PinIcon,
  CommentDiscussionIcon,
  TrophyIcon,
  LawIcon,
  ThumbsupIcon,
  HeartFillIcon,
  FileBadgeIcon,
  PackageIcon,
  IssueClosedIcon,
  OrganizationIcon,
  FileDirectoryFillIcon,
  CheckIcon,
  StackIcon,
  DashIcon,
  LightBulbIcon,
  CopilotErrorIcon,
  IssueTracksIcon,
  IssueTrackedByIcon,
  CopilotWarningIcon,
  EyeClosedIcon,
  ListUnorderedIcon,
  DiffIcon,
  FlameIcon,
  FileSymlinkFileIcon,
  PasteIcon,
  IssueOpenedIcon,
  CodeSquareIcon,
  ShieldIcon,
  PlusCircleIcon,
  DotFillIcon,
  PlusIcon,
  TriangleDownIcon,
  CopilotIcon,
  XCircleIcon,
} from '@primer/octicons-react'
figma.connect(InfinityIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-890', {
  example: () => <InfinityIcon size={24} />,
})

figma.connect(FileBinaryIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-874', {
  example: () => <FileBinaryIcon size={24} />,
})

figma.connect(PackageDependenciesIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-124', {
  example: () => <PackageDependenciesIcon size={16} />,
})

figma.connect(ArrowUpLeftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=246-89', {
  example: () => <ArrowUpLeftIcon size={16} />,
})

figma.connect(RubyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=966-31', {
  example: () => <RubyIcon size={24} />,
})

figma.connect(PackageDependentsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-968', {
  example: () => <PackageDependentsIcon size={24} />,
})

figma.connect(DiffRenamedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-248', {
  example: () => <DiffRenamedIcon size={16} />,
})

figma.connect(HourglassIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-922', {
  example: () => <HourglassIcon size={24} />,
})

figma.connect(MoveToStartIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4549-156', {
  example: () => <MoveToStartIcon size={24} />,
})

figma.connect(TabIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-868', {
  example: () => <TabIcon size={24} />,
})

figma.connect(GitPullRequestIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-879', {
  example: () => <GitPullRequestIcon size={24} />,
})

figma.connect(AccessibilityInsetIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5480-624', {
  example: () => <AccessibilityInsetIcon size={16} />,
})

figma.connect(GoalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4238-103', {
  example: () => <GoalIcon size={24} />,
})

figma.connect(ZoomOutIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4640-117', {
  example: () => <ZoomOutIcon size={24} />,
})

figma.connect(LogoGithubIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=181-956', {
  example: () => <LogoGithubIcon size={24} />,
})

figma.connect(FileMediaIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1006', {
  example: () => <FileMediaIcon size={24} />,
})

figma.connect(ChevronRightIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-290', {
  example: () => <ChevronRightIcon size={16} />,
})

figma.connect(FiscalHostIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5456-399', {
  example: () => <FiscalHostIcon size={24} />,
})

figma.connect(DiffRemovedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5478-548', {
  example: () => <DiffRemovedIcon size={24} />,
})

figma.connect(DiffRenamedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5478-545', {
  example: () => <DiffRenamedIcon size={24} />,
})

figma.connect(FileMovedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5458-470', {
  example: () => <FileMovedIcon size={24} />,
})

figma.connect(MoveToBottomIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4986-139', {
  example: () => <MoveToBottomIcon size={16} />,
})

figma.connect(XIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-915', {
  example: () => <XIcon size={24} />,
})

figma.connect(DiffRemovedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-250', {
  example: () => <DiffRemovedIcon size={16} />,
})

figma.connect(PaperAirplaneIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-120', {
  example: () => <PaperAirplaneIcon size={16} />,
})

figma.connect(HashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1767-37', {
  example: () => <HashIcon size={16} />,
})

figma.connect(UndoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5451-218', {
  example: () => <UndoIcon size={24} />,
})

figma.connect(UnlinkIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4297-115', {
  example: () => <UnlinkIcon size={16} />,
})

figma.connect(EllipsisIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=966-39', {
  example: () => <EllipsisIcon size={16} />,
})

figma.connect(VideoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1737-12', {
  example: () => <VideoIcon size={24} />,
})

figma.connect(KebabHorizontalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-162', {
  example: () => <KebabHorizontalIcon size={16} />,
})

figma.connect(ArrowBothIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-329', {
  example: () => <ArrowBothIcon size={16} />,
})

figma.connect(ServerIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-72', {
  example: () => <ServerIcon size={16} />,
})

figma.connect(StopIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-921', {
  example: () => <StopIcon size={24} />,
})

figma.connect(SquareFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=949-43', {
  example: () => <SquareFillIcon size={16} />,
})

figma.connect(SmileyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1023', {
  example: () => <SmileyIcon size={24} />,
})

figma.connect(CreditCardIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-268', {
  example: () => <CreditCardIcon size={16} />,
})

figma.connect(PivotColumnIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5153-113', {
  example: () => <PivotColumnIcon size={16} />,
})

figma.connect(HeartIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-190', {
  example: () => <HeartIcon size={16} />,
})

figma.connect(ListOrderedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-150', {
  example: () => <ListOrderedIcon size={16} />,
})

figma.connect(ItalicIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-166', {
  example: () => <ItalicIcon size={16} />,
})

figma.connect(CircleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=964-32', {
  example: () => <CircleIcon size={16} />,
})

figma.connect(CodeOfConductIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2766-227', {
  example: () => <CodeOfConductIcon size={24} />,
})

figma.connect(BellFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-909', {
  example: () => <BellFillIcon size={24} />,
})

figma.connect(TelescopeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1003', {
  example: () => <TelescopeIcon size={24} />,
})

figma.connect(ArrowUpIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-321', {
  example: () => <ArrowUpIcon size={16} />,
})

figma.connect(XCircleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=964-28', {
  example: () => <XCircleIcon size={16} />,
})

figma.connect(QuestionIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-970', {
  example: () => <QuestionIcon size={24} />,
})

figma.connect(ScreenFullIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-78', {
  example: () => <ScreenFullIcon size={16} />,
})

figma.connect(ShieldCheckIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-64', {
  example: () => <ShieldCheckIcon size={16} />,
})

figma.connect(ArrowLeftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-914', {
  example: () => <ArrowLeftIcon size={24} />,
})

figma.connect(SyncIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-46', {
  example: () => <SyncIcon size={16} />,
})

figma.connect(VersionsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-4', {
  example: () => <VersionsIcon size={16} />,
})

figma.connect(IdBadgeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5453-380', {
  example: () => <IdBadgeIcon size={24} />,
})

figma.connect(IterationsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2575-77', {
  example: () => <IterationsIcon size={16} />,
})

figma.connect(AlertFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3971-108', {
  example: () => <AlertFillIcon size={24} />,
})

figma.connect(RowsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2062-8', {
  example: () => <RowsIcon size={16} />,
})

figma.connect(GitMergeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-877', {
  example: () => <GitMergeIcon size={24} />,
})

figma.connect(ShieldCheckIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-940', {
  example: () => <ShieldCheckIcon size={24} />,
})

figma.connect(DownloadIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4549-153', {
  example: () => <DownloadIcon size={16} />,
})

figma.connect(FileIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-234', {
  example: () => <FileIcon size={16} />,
})

figma.connect(SlidersIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3456-103', {
  example: () => <SlidersIcon size={16} />,
})

figma.connect(RocketIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-900', {
  example: () => <RocketIcon size={24} />,
})

figma.connect(ChevronLeftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4508-141', {
  example: () => <ChevronLeftIcon size={12} />,
})

figma.connect(HomeFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1033', {
  example: () => <HomeFillIcon size={24} />,
})

figma.connect(GrabberIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-864', {
  example: () => <GrabberIcon size={24} />,
})

figma.connect(ZoomInIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4640-122', {
  example: () => <ZoomInIcon size={16} />,
})

figma.connect(StarFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-939', {
  example: () => <StarFillIcon size={24} />,
})

figma.connect(RedoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5452-326', {
  example: () => <RedoIcon size={24} />,
})

figma.connect(FileRemovedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3480-123', {
  example: () => <FileRemovedIcon size={16} />,
})

figma.connect(ChevronDownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-294', {
  example: () => <ChevronDownIcon size={16} />,
})

figma.connect(SidebarCollapseIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3757-124', {
  example: () => <SidebarCollapseIcon size={24} />,
})

figma.connect(SkipFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4119-125', {
  example: () => <SkipFillIcon size={24} />,
})

figma.connect(ZapIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=966-35', {
  example: () => <ZapIcon size={16} />,
})

figma.connect(SearchIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-74', {
  example: () => <SearchIcon size={16} />,
})

figma.connect(MarkGithubIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-947', {
  example: () => <MarkGithubIcon size={24} />,
})

figma.connect(PeopleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1034', {
  example: () => <PeopleIcon size={24} />,
})

figma.connect(HeadingIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-957', {
  example: () => <HeadingIcon size={24} />,
})

figma.connect(DiamondIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2061-1', {
  example: () => <DiamondIcon size={24} />,
})

figma.connect(ArrowSwitchIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3042-222', {
  example: () => <ArrowSwitchIcon size={24} />,
})

figma.connect(PinSlashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4986-122', {
  example: () => <PinSlashIcon size={24} />,
})

figma.connect(LocationIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-903', {
  example: () => <LocationIcon size={24} />,
})

figma.connect(CircleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1051', {
  example: () => <CircleIcon size={24} />,
})

figma.connect(ArrowUpRightIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=246-101', {
  example: () => <ArrowUpRightIcon size={24} />,
})

figma.connect(SparkleFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5451-290', {
  example: () => <SparkleFillIcon size={24} />,
})

figma.connect(TrashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-893', {
  example: () => <TrashIcon size={24} />,
})

figma.connect(SlidersIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5452-301', {
  example: () => <SlidersIcon size={24} />,
})

figma.connect(ArrowUpLeftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-912', {
  example: () => <ArrowUpLeftIcon size={24} />,
})

figma.connect(FileDirectoryOpenFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5458-441', {
  example: () => <FileDirectoryOpenFillIcon size={24} />,
})

figma.connect(ShareAndroidIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-994', {
  example: () => <ShareAndroidIcon size={24} />,
})

figma.connect(DuplicateIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2384-79', {
  example: () => <DuplicateIcon size={24} />,
})

figma.connect(FoldUpIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-932', {
  example: () => <FoldUpIcon size={24} />,
})

figma.connect(GitCommitIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-882', {
  example: () => <GitCommitIcon size={24} />,
})

figma.connect(BellIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-911', {
  example: () => <BellIcon size={24} />,
})

figma.connect(FileCodeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-873', {
  example: () => <FileCodeIcon size={24} />,
})

figma.connect(BookmarkSlashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1027', {
  example: () => <BookmarkSlashIcon size={24} />,
})

figma.connect(BellSlashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-908', {
  example: () => <BellSlashIcon size={24} />,
})

figma.connect(MegaphoneIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-979', {
  example: () => <MegaphoneIcon size={24} />,
})

figma.connect(PaperAirplaneIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-937', {
  example: () => <PaperAirplaneIcon size={24} />,
})

figma.connect(CommandPaletteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3763-106', {
  example: () => <CommandPaletteIcon size={24} />,
})

figma.connect(ArrowBothIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-880', {
  example: () => <ArrowBothIcon size={24} />,
})

figma.connect(TriangleRightIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-885', {
  example: () => <TriangleRightIcon size={24} />,
})

figma.connect(ProjectRoadmapIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4119-121', {
  example: () => <ProjectRoadmapIcon size={24} />,
})

figma.connect(NumberIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1960-5', {
  example: () => <NumberIcon size={24} />,
})

figma.connect(PaperclipIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3751-106', {
  example: () => <PaperclipIcon size={24} />,
})

figma.connect(TriangleUpIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-927', {
  example: () => <TriangleUpIcon size={24} />,
})

figma.connect(ChevronUpIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-883', {
  example: () => <ChevronUpIcon size={24} />,
})

figma.connect(ItalicIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-986', {
  example: () => <ItalicIcon size={24} />,
})

figma.connect(ServerIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1002', {
  example: () => <ServerIcon size={24} />,
})

figma.connect(ChevronLeftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-881', {
  example: () => <ChevronLeftIcon size={24} />,
})

figma.connect(FileSubmoduleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-996', {
  example: () => <FileSubmoduleIcon size={24} />,
})

figma.connect(AccessibilityInsetIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5480-606', {
  example: () => <AccessibilityInsetIcon size={24} />,
})

figma.connect(MortarBoardIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-866', {
  example: () => <MortarBoardIcon size={24} />,
})

figma.connect(NoteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1017', {
  example: () => <NoteIcon size={24} />,
})

figma.connect(CodescanIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1944-12', {
  example: () => <CodescanIcon size={24} />,
})

figma.connect(WorkflowIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-899', {
  example: () => <WorkflowIcon size={24} />,
})

figma.connect(CommentIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-948', {
  example: () => <CommentIcon size={24} />,
})

figma.connect(ArrowRightIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-918', {
  example: () => <ArrowRightIcon size={24} />,
})

figma.connect(CreditCardIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-928', {
  example: () => <CreditCardIcon size={24} />,
})

figma.connect(FileRemovedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5458-457', {
  example: () => <FileRemovedIcon size={24} />,
})

figma.connect(FileIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-871', {
  example: () => <FileIcon size={24} />,
})

figma.connect(SunIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=857-26', {
  example: () => <SunIcon size={24} />,
})

figma.connect(DiffModifiedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5478-546', {
  example: () => <DiffModifiedIcon size={24} />,
})

figma.connect(HorizontalRuleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-990', {
  example: () => <HorizontalRuleIcon size={24} />,
})

figma.connect(ContainerIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1508-116', {
  example: () => <ContainerIcon size={24} />,
})

figma.connect(EyeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1011', {
  example: () => <EyeIcon size={24} />,
})

figma.connect(CloudOfflineIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3148-217', {
  example: () => <CloudOfflineIcon size={24} />,
})

figma.connect(UnlockIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-980', {
  example: () => <UnlockIcon size={24} />,
})

figma.connect(ShieldXIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1049', {
  example: () => <ShieldXIcon size={24} />,
})

figma.connect(CrossReferenceIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-925', {
  example: () => <CrossReferenceIcon size={24} />,
})

figma.connect(BookmarkFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-967', {
  example: () => <BookmarkFillIcon size={24} />,
})

figma.connect(ThumbsdownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-998', {
  example: () => <ThumbsdownIcon size={24} />,
})

figma.connect(HashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1767-15', {
  example: () => <HashIcon size={24} />,
})

figma.connect(DeviceMobileIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-989', {
  example: () => <DeviceMobileIcon size={24} />,
})

figma.connect(BookmarkSlashFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1030', {
  example: () => <BookmarkSlashFillIcon size={24} />,
})

figma.connect(DesktopDownloadIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-991', {
  example: () => <DesktopDownloadIcon size={24} />,
})

figma.connect(CodeReviewIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-923', {
  example: () => <CodeReviewIcon size={24} />,
})

figma.connect(FoldDownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-887', {
  example: () => <FoldDownIcon size={24} />,
})

figma.connect(CloudIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3121-241', {
  example: () => <CloudIcon size={24} />,
})

figma.connect(MirrorIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-938', {
  example: () => <MirrorIcon size={24} />,
})

figma.connect(MarkdownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-995', {
  example: () => <MarkdownIcon size={24} />,
})

figma.connect(MoveToBottomIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4986-156', {
  example: () => <MoveToBottomIcon size={24} />,
})

figma.connect(SortAscIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2117-82', {
  example: () => <SortAscIcon size={24} />,
})

figma.connect(BrowserIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1917-82', {
  example: () => <BrowserIcon size={24} />,
})

figma.connect(SidebarExpandIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3757-123', {
  example: () => <SidebarExpandIcon size={24} />,
})

figma.connect(ColumnsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2062-7', {
  example: () => <ColumnsIcon size={24} />,
})

figma.connect(SquirrelIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1000-26', {
  example: () => <SquirrelIcon size={24} />,
})

figma.connect(MoveToTopIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4986-155', {
  example: () => <MoveToTopIcon size={24} />,
})

figma.connect(UnverifiedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-984', {
  example: () => <UnverifiedIcon size={24} />,
})

figma.connect(PersonIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-905', {
  example: () => <PersonIcon size={24} />,
})

figma.connect(LogIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3967-103', {
  example: () => <LogIcon size={24} />,
})

figma.connect(TypographyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1047', {
  example: () => <TypographyIcon size={24} />,
})

figma.connect(ScreenFullIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1018', {
  example: () => <ScreenFullIcon size={24} />,
})

figma.connect(FeedMergedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3071-224', {
  example: () => <FeedMergedIcon size={16} />,
})

figma.connect(DeviceCameraVideoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-985', {
  example: () => <DeviceCameraVideoIcon size={24} />,
})

figma.connect(BoldIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-999', {
  example: () => <BoldIcon size={24} />,
})

figma.connect(ToolsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-891', {
  example: () => <ToolsIcon size={24} />,
})

figma.connect(FileDiffIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-870', {
  example: () => <FileDiffIcon size={24} />,
})

figma.connect(CpuIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-944', {
  example: () => <CpuIcon size={24} />,
})

figma.connect(NorthStarIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=184-6', {
  example: () => <NorthStarIcon size={24} />,
})

figma.connect(HistoryIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-953', {
  example: () => <HistoryIcon size={24} />,
})

figma.connect(FoldIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1024', {
  example: () => <FoldIcon size={24} />,
})

figma.connect(PivotColumnIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5153-110', {
  example: () => <PivotColumnIcon size={24} />,
})

figma.connect(MentionIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-930', {
  example: () => <MentionIcon size={24} />,
})

figma.connect(DotIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1045', {
  example: () => <DotIcon size={24} />,
})

figma.connect(ChevronRightIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4502-199', {
  example: () => <ChevronRightIcon size={12} />,
})

figma.connect(LockIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-961', {
  example: () => <LockIcon size={24} />,
})

figma.connect(QuoteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-971', {
  example: () => <QuoteIcon size={24} />,
})

figma.connect(ScreenNormalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-941', {
  example: () => <ScreenNormalIcon size={24} />,
})

figma.connect(BroadcastIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-889', {
  example: () => <BroadcastIcon size={24} />,
})

figma.connect(RepoPushIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-963', {
  example: () => <RepoPushIcon size={24} />,
})

figma.connect(HubotIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1028', {
  example: () => <HubotIcon size={24} />,
})

figma.connect(ShieldLockIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1019', {
  example: () => <ShieldLockIcon size={24} />,
})

figma.connect(ChevronDownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-978', {
  example: () => <ChevronDownIcon size={24} />,
})

figma.connect(GitBranchIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-878', {
  example: () => <GitBranchIcon size={24} />,
})

figma.connect(MuteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1020', {
  example: () => <MuteIcon size={24} />,
})

figma.connect(DependabotIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1944-14', {
  example: () => <DependabotIcon size={24} />,
})

figma.connect(DiffAddedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5478-549', {
  example: () => <DiffAddedIcon size={24} />,
})

figma.connect(FilterIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-942', {
  example: () => <FilterIcon size={24} />,
})

figma.connect(PulseIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1035', {
  example: () => <PulseIcon size={24} />,
})

figma.connect(TabExternalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5451-278', {
  example: () => <TabExternalIcon size={24} />,
})

figma.connect(RelFilePathIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4223-108', {
  example: () => <RelFilePathIcon size={24} />,
})

figma.connect(ArchiveIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1009', {
  example: () => <ArchiveIcon size={24} />,
})

figma.connect(UnmuteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-997', {
  example: () => <UnmuteIcon size={24} />,
})

figma.connect(SkipIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1041', {
  example: () => <SkipIcon size={24} />,
})

figma.connect(ListOrderedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-946', {
  example: () => <ListOrderedIcon size={24} />,
})

figma.connect(FileZipIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-910', {
  example: () => <FileZipIcon size={24} />,
})

figma.connect(GitPullRequestClosedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2059-94', {
  example: () => <GitPullRequestClosedIcon size={24} />,
})

figma.connect(RepoLockedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3217-224', {
  example: () => <RepoLockedIcon size={24} />,
})

figma.connect(CircleSlashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1031', {
  example: () => <CircleSlashIcon size={24} />,
})

figma.connect(FileAddedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5458-477', {
  example: () => <FileAddedIcon size={24} />,
})

figma.connect(ReplyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-895', {
  example: () => <ReplyIcon size={24} />,
})

figma.connect(InboxIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1032', {
  example: () => <InboxIcon size={24} />,
})

figma.connect(PlugIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-972', {
  example: () => <PlugIcon size={24} />,
})

figma.connect(StrikethroughIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1554-89', {
  example: () => <StrikethroughIcon size={24} />,
})

figma.connect(UnfoldIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-888', {
  example: () => <UnfoldIcon size={24} />,
})

figma.connect(TriangleLeftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-884', {
  example: () => <TriangleLeftIcon size={24} />,
})

figma.connect(MultiSelectIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1666-79', {
  example: () => <MultiSelectIcon size={24} />,
})

figma.connect(RssIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-926', {
  example: () => <RssIcon size={24} />,
})

figma.connect(RepoDeletedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5452-315', {
  example: () => <RepoDeletedIcon size={24} />,
})

figma.connect(GiftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1025', {
  example: () => <GiftIcon size={24} />,
})

figma.connect(DatabaseIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-264', {
  example: () => <DatabaseIcon size={16} />,
})

figma.connect(SquareFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=949-83', {
  example: () => <SquareFillIcon size={24} />,
})

figma.connect(SingleSelectIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2062-17', {
  example: () => <SingleSelectIcon size={16} />,
})

figma.connect(QuoteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-96', {
  example: () => <QuoteIcon size={16} />,
})

figma.connect(FeedRocketIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2772-549', {
  example: () => <FeedRocketIcon size={16} />,
})

figma.connect(WebhookIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2975-235', {
  example: () => <WebhookIcon size={16} />,
})

figma.connect(SortDescIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2117-83', {
  example: () => <SortDescIcon size={24} />,
})

figma.connect(HeadingIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-192', {
  example: () => <HeadingIcon size={16} />,
})

figma.connect(ArrowDownRightIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=246-90', {
  example: () => <ArrowDownRightIcon size={16} />,
})

figma.connect(SquareIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=949-82', {
  example: () => <SquareIcon size={24} />,
})

figma.connect(SortDescIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2117-81', {
  example: () => <SortDescIcon size={16} />,
})

figma.connect(ChevronUpIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4445-118', {
  example: () => <ChevronUpIcon size={12} />,
})

figma.connect(SponsorTiersIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4297-130', {
  example: () => <SponsorTiersIcon size={24} />,
})

figma.connect(KeyAsteriskIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5452-370', {
  example: () => <KeyAsteriskIcon size={24} />,
})

figma.connect(ArrowDownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-327', {
  example: () => <ArrowDownIcon size={16} />,
})

figma.connect(MoveToTopIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4986-137', {
  example: () => <MoveToTopIcon size={16} />,
})

figma.connect(SignOutIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=72-2042', {
  example: () => <SignOutIcon size={16} />,
})

figma.connect(BroadcastIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-304', {
  example: () => <BroadcastIcon size={16} />,
})

figma.connect(PaintbrushIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1000-48', {
  example: () => <PaintbrushIcon size={24} />,
})

figma.connect(CacheIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3735-109', {
  example: () => <CacheIcon size={16} />,
})

figma.connect(ChevronLeftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-292', {
  example: () => <ChevronLeftIcon size={16} />,
})

figma.connect(MoveToEndIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4549-157', {
  example: () => <MoveToEndIcon size={24} />,
})

figma.connect(SunIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=857-34', {
  example: () => <SunIcon size={16} />,
})

figma.connect(ReportIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=949-74', {
  example: () => <ReportIcon size={16} />,
})

figma.connect(SignOutIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-901', {
  example: () => <SignOutIcon size={24} />,
})

figma.connect(PersonFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2510-78', {
  example: () => <PersonFillIcon size={16} />,
})

figma.connect(EllipsisIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5460-511', {
  example: () => <EllipsisIcon size={24} />,
})

figma.connect(ZoomOutIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4640-123', {
  example: () => <ZoomOutIcon size={16} />,
})

figma.connect(ArrowDownLeftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=246-88', {
  example: () => <ArrowDownLeftIcon size={16} />,
})

figma.connect(SidebarExpandIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3757-107', {
  example: () => <SidebarExpandIcon size={16} />,
})

figma.connect(ShieldSlashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3849-103', {
  example: () => <ShieldSlashIcon size={16} />,
})

figma.connect(HorizontalRuleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=186-6', {
  example: () => <HorizontalRuleIcon size={16} />,
})

figma.connect(NoEntryFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2617-91', {
  example: () => <NoEntryFillIcon size={12} />,
})

figma.connect(BeakerIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1014', {
  example: () => <BeakerIcon size={24} />,
})

figma.connect(CloudIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3121-221', {
  example: () => <CloudIcon size={16} />,
})

figma.connect(FeedDiscussionIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2772-555', {
  example: () => <FeedDiscussionIcon size={16} />,
})

figma.connect(UndoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5448-193', {
  example: () => <UndoIcon size={16} />,
})

figma.connect(TriangleLeftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-24', {
  example: () => <TriangleLeftIcon size={16} />,
})

figma.connect(NoEntryIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2595-86', {
  example: () => <NoEntryIcon size={24} />,
})

figma.connect(UnverifiedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-10', {
  example: () => <UnverifiedIcon size={16} />,
})

figma.connect(ShareIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1117-74', {
  example: () => <ShareIcon size={24} />,
})

figma.connect(CopyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1923-82', {
  example: () => <CopyIcon size={16} />,
})

figma.connect(CopyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1923-94', {
  example: () => <CopyIcon size={24} />,
})

figma.connect(DiamondIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2061-0', {
  example: () => <DiamondIcon size={16} />,
})

figma.connect(LogoGistIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5452-340', {
  example: () => <LogoGistIcon size={24} />,
})

figma.connect(UnreadIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4297-106', {
  example: () => <UnreadIcon size={16} />,
})

figma.connect(MirrorIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=20-74', {
  example: () => <MirrorIcon size={16} />,
})

figma.connect(TasklistIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-974', {
  example: () => <TasklistIcon size={24} />,
})

figma.connect(ReplyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-94', {
  example: () => <ReplyIcon size={16} />,
})

figma.connect(TasklistIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-42', {
  example: () => <TasklistIcon size={16} />,
})

figma.connect(CodeOfConductIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2766-221', {
  example: () => <CodeOfConductIcon size={16} />,
})

figma.connect(UnlinkIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4297-118', {
  example: () => <UnlinkIcon size={24} />,
})

figma.connect(UnreadIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4297-112', {
  example: () => <UnreadIcon size={24} />,
})

figma.connect(ShieldSlashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4715-108', {
  example: () => <ShieldSlashIcon size={24} />,
})

figma.connect(PackageDependenciesIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-931', {
  example: () => <PackageDependenciesIcon size={24} />,
})

figma.connect(InfinityIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-176', {
  example: () => <InfinityIcon size={16} />,
})

figma.connect(CodescanIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1944-23', {
  example: () => <CodescanIcon size={16} />,
})

figma.connect(FeedHeartIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2772-553', {
  example: () => <FeedHeartIcon size={16} />,
})

figma.connect(SortAscIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2117-80', {
  example: () => <SortAscIcon size={16} />,
})

figma.connect(IterationsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2577-89', {
  example: () => <IterationsIcon size={24} />,
})

figma.connect(IssueReopenedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-168', {
  example: () => <IssueReopenedIcon size={16} />,
})

figma.connect(GitMergeQueueIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3751-103', {
  example: () => <GitMergeQueueIcon size={16} />,
})

figma.connect(FeedPersonIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2772-551', {
  example: () => <FeedPersonIcon size={16} />,
})

figma.connect(NorthStarIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=184-4', {
  example: () => <NorthStarIcon size={16} />,
})

figma.connect(PersonFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2558-77', {
  example: () => <PersonFillIcon size={24} />,
})

figma.connect(FeedRepoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2772-554', {
  example: () => <FeedRepoIcon size={16} />,
})

figma.connect(IssueDraftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2246-22', {
  example: () => <IssueDraftIcon size={24} />,
})

figma.connect(ArrowDownLeftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=246-102', {
  example: () => <ArrowDownLeftIcon size={24} />,
})

figma.connect(MoonIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=858-2', {
  example: () => <MoonIcon size={16} />,
})

figma.connect(MoonIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=857-27', {
  example: () => <MoonIcon size={24} />,
})

figma.connect(ArrowDownRightIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=246-100', {
  example: () => <ArrowDownRightIcon size={24} />,
})

figma.connect(CommandPaletteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3763-105', {
  example: () => <CommandPaletteIcon size={16} />,
})

figma.connect(AccessibilityIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2975-246', {
  example: () => <AccessibilityIcon size={16} />,
})

figma.connect(ArrowUpIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-916', {
  example: () => <ArrowUpIcon size={24} />,
})

figma.connect(AppsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5420-122', {
  example: () => <AppsIcon size={24} />,
})

figma.connect(CloudOfflineIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3148-214', {
  example: () => <CloudOfflineIcon size={16} />,
})

figma.connect(LinkIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-902', {
  example: () => <LinkIcon size={24} />,
})

figma.connect(TypographyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-18', {
  example: () => <TypographyIcon size={16} />,
})

figma.connect(AccessibilityIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5480-652', {
  example: () => <AccessibilityIcon size={24} />,
})

figma.connect(ZoomInIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4640-116', {
  example: () => <ZoomInIcon size={24} />,
})

figma.connect(PlayIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1008', {
  example: () => <PlayIcon size={24} />,
})

figma.connect(RepoForkedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-90', {
  example: () => <RepoForkedIcon size={16} />,
})

figma.connect(FileBinaryIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=32-97', {
  example: () => <FileBinaryIcon size={16} />,
})

figma.connect(SkipIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-58', {
  example: () => <SkipIcon size={16} />,
})

figma.connect(TerminalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-906', {
  example: () => <TerminalIcon size={24} />,
})

figma.connect(DiffIgnoredIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5478-547', {
  example: () => <DiffIgnoredIcon size={24} />,
})

figma.connect(TriangleUpIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-20', {
  example: () => <TriangleUpIcon size={16} />,
})

figma.connect(BlockedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1923-78', {
  example: () => <BlockedIcon size={16} />,
})

figma.connect(BoldIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-312', {
  example: () => <BoldIcon size={16} />,
})

figma.connect(CodescanCheckmarkIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1944-13', {
  example: () => <CodescanCheckmarkIcon size={24} />,
})

figma.connect(InfoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-993', {
  example: () => <InfoIcon size={24} />,
})

figma.connect(GitPullRequestDraftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2059-89', {
  example: () => <GitPullRequestDraftIcon size={16} />,
})

figma.connect(PackageDependentsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-122', {
  example: () => <PackageDependentsIcon size={16} />,
})

figma.connect(RepoTemplateIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-86', {
  example: () => <RepoTemplateIcon size={16} />,
})

figma.connect(SignInIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=72-2045', {
  example: () => <SignInIcon size={16} />,
})

figma.connect(ScreenNormalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-76', {
  example: () => <ScreenNormalIcon size={16} />,
})

figma.connect(CodeReviewIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-278', {
  example: () => <CodeReviewIcon size={16} />,
})

figma.connect(FeedStarIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2772-552', {
  example: () => <FeedStarIcon size={16} />,
})

figma.connect(DeviceDesktopIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-892', {
  example: () => <DeviceDesktopIcon size={24} />,
})

figma.connect(SkipFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4119-123', {
  example: () => <SkipFillIcon size={16} />,
})

figma.connect(EyeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-238', {
  example: () => <EyeIcon size={16} />,
})

figma.connect(IssueDraftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2246-19', {
  example: () => <IssueDraftIcon size={16} />,
})

figma.connect(RowsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2062-6', {
  example: () => <RowsIcon size={24} />,
})

figma.connect(BugIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2314-132', {
  example: () => <BugIcon size={16} />,
})

figma.connect(LinkExternalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1016', {
  example: () => <LinkExternalIcon size={24} />,
})

figma.connect(SignInIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-952', {
  example: () => <SignInIcon size={24} />,
})

figma.connect(RssIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-80', {
  example: () => <RssIcon size={16} />,
})

figma.connect(LogoGistIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5452-335', {
  example: () => <LogoGistIcon size={16} />,
})

figma.connect(GitCompareIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-204', {
  example: () => <GitCompareIcon size={16} />,
})

figma.connect(ReportIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=949-76', {
  example: () => <ReportIcon size={24} />,
})

figma.connect(PersonIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-114', {
  example: () => <PersonIcon size={16} />,
})

figma.connect(FeedTagIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2772-547', {
  example: () => <FeedTagIcon size={16} />,
})

figma.connect(DiffAddedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-256', {
  example: () => <DiffAddedIcon size={16} />,
})

figma.connect(RepoTemplateIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1012', {
  example: () => <RepoTemplateIcon size={24} />,
})

figma.connect(FeedForkedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3071-225', {
  example: () => <FeedForkedIcon size={16} />,
})

figma.connect(NumberIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1958-5', {
  example: () => <NumberIcon size={16} />,
})

figma.connect(ShieldXIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-60', {
  example: () => <ShieldXIcon size={16} />,
})

figma.connect(SquareIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=949-42', {
  example: () => <SquareIcon size={16} />,
})

figma.connect(BriefcaseIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=966-27', {
  example: () => <BriefcaseIcon size={24} />,
})

figma.connect(KebabHorizontalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1046', {
  example: () => <KebabHorizontalIcon size={24} />,
})

figma.connect(KeyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1044', {
  example: () => <KeyIcon size={24} />,
})

figma.connect(MailIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1015', {
  example: () => <MailIcon size={24} />,
})

figma.connect(BlockedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1923-93', {
  example: () => <BlockedIcon size={24} />,
})

figma.connect(FeedTrophyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3071-226', {
  example: () => <FeedTrophyIcon size={16} />,
})

figma.connect(ContainerIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1508-131', {
  example: () => <ContainerIcon size={16} />,
})

figma.connect(PersonAddIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1910-76', {
  example: () => <PersonAddIcon size={16} />,
})

figma.connect(DependabotIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1944-21', {
  example: () => <DependabotIcon size={16} />,
})

figma.connect(DiffIgnoredIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-254', {
  example: () => <DiffIgnoredIcon size={16} />,
})

figma.connect(FileMovedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3480-122', {
  example: () => <FileMovedIcon size={16} />,
})

figma.connect(RepoDeletedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2975-243', {
  example: () => <RepoDeletedIcon size={16} />,
})

figma.connect(MeterIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1000-47', {
  example: () => <MeterIcon size={24} />,
})

figma.connect(StopwatchIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1010', {
  example: () => <StopwatchIcon size={24} />,
})

figma.connect(CodescanCheckmarkIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1944-22', {
  example: () => <CodescanCheckmarkIcon size={16} />,
})

figma.connect(ProjectSymlinkIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4119-122', {
  example: () => <ProjectSymlinkIcon size={24} />,
})

figma.connect(TelescopeFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2558-74', {
  example: () => <TelescopeFillIcon size={24} />,
})

figma.connect(UploadIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4549-159', {
  example: () => <UploadIcon size={24} />,
})

figma.connect(MoveToEndIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4548-129', {
  example: () => <MoveToEndIcon size={16} />,
})

figma.connect(MoveToStartIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4548-128', {
  example: () => <MoveToStartIcon size={16} />,
})

figma.connect(PinSlashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4986-115', {
  example: () => <PinSlashIcon size={16} />,
})

figma.connect(SidebarCollapseIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3757-108', {
  example: () => <SidebarCollapseIcon size={16} />,
})

figma.connect(MentionIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-138', {
  example: () => <MentionIcon size={16} />,
})

figma.connect(CacheIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5480-568', {
  example: () => <CacheIcon size={24} />,
})

figma.connect(XCircleFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-966', {
  example: () => <XCircleFillIcon size={24} />,
})

figma.connect(TriangleRightIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-22', {
  example: () => <TriangleRightIcon size={16} />,
})

figma.connect(HubotIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-182', {
  example: () => <HubotIcon size={16} />,
})

figma.connect(TableIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1914-7', {
  example: () => <TableIcon size={16} />,
})

figma.connect(HomeFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5448-177', {
  example: () => <HomeFillIcon size={16} />,
})

figma.connect(StarIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-54', {
  example: () => <StarIcon size={16} />,
})

figma.connect(AlertFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3971-109', {
  example: () => <AlertFillIcon size={16} />,
})

figma.connect(AlertIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-333', {
  example: () => <AlertIcon size={16} />,
})

figma.connect(HeartIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-981', {
  example: () => <HeartIcon size={24} />,
})

figma.connect(PersonAddIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1910-79', {
  example: () => <PersonAddIcon size={24} />,
})

figma.connect(HistoryIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-186', {
  example: () => <HistoryIcon size={16} />,
})

figma.connect(MailIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-142', {
  example: () => <MailIcon size={16} />,
})

figma.connect(KeyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-160', {
  example: () => <KeyIcon size={16} />,
})

figma.connect(TelescopeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-40', {
  example: () => <TelescopeIcon size={16} />,
})

figma.connect(LocationIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-146', {
  example: () => <LocationIcon size={16} />,
})

figma.connect(BrowserIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1917-85', {
  example: () => <BrowserIcon size={16} />,
})

figma.connect(SponsorTiersIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4297-126', {
  example: () => <SponsorTiersIcon size={16} />,
})

figma.connect(DeviceCameraVideoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-262', {
  example: () => <DeviceCameraVideoIcon size={16} />,
})

figma.connect(PaintbrushIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=949-41', {
  example: () => <PaintbrushIcon size={16} />,
})

figma.connect(UnmuteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-12', {
  example: () => <UnmuteIcon size={16} />,
})

figma.connect(ArchiveIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-331', {
  example: () => <ArchiveIcon size={16} />,
})

figma.connect(PlugIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-108', {
  example: () => <PlugIcon size={16} />,
})

figma.connect(TelescopeFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2510-81', {
  example: () => <TelescopeFillIcon size={16} />,
})

figma.connect(RubyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=966-33', {
  example: () => <RubyIcon size={16} />,
})

figma.connect(MeterIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=949-40', {
  example: () => <MeterIcon size={16} />,
})

figma.connect(BookmarkSlashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-306', {
  example: () => <BookmarkSlashIcon size={16} />,
})

figma.connect(KeyAsteriskIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2176-4', {
  example: () => <KeyAsteriskIcon size={16} />,
})

figma.connect(GiftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-210', {
  example: () => <GiftIcon size={16} />,
})

figma.connect(TagIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-44', {
  example: () => <TagIcon size={16} />,
})

figma.connect(IdBadgeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2975-233', {
  example: () => <IdBadgeIcon size={16} />,
})

figma.connect(GearIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-212', {
  example: () => <GearIcon size={16} />,
})

figma.connect(BriefcaseIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=966-37', {
  example: () => <BriefcaseIcon size={16} />,
})

figma.connect(UnlockIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-14', {
  example: () => <UnlockIcon size={16} />,
})

figma.connect(HourglassIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=72-2031', {
  example: () => <HourglassIcon size={16} />,
})

figma.connect(FiscalHostIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4525-108', {
  example: () => <FiscalHostIcon size={16} />,
})

figma.connect(BellSlashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-314', {
  example: () => <BellSlashIcon size={16} />,
})

figma.connect(ImageIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-180', {
  example: () => <ImageIcon size={16} />,
})

figma.connect(ClockIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-282', {
  example: () => <ClockIcon size={16} />,
})

figma.connect(BookIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-310', {
  example: () => <BookIcon size={16} />,
})

figma.connect(MortarBoardIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-134', {
  example: () => <MortarBoardIcon size={16} />,
})

figma.connect(DeviceMobileIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-260', {
  example: () => <DeviceMobileIcon size={16} />,
})

figma.connect(MegaphoneIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=17-2', {
  example: () => <MegaphoneIcon size={16} />,
})

figma.connect(ProjectIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-102', {
  example: () => <ProjectIcon size={16} />,
})

figma.connect(GraphIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-194', {
  example: () => <GraphIcon size={16} />,
})

figma.connect(SquirrelIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=949-92', {
  example: () => <SquirrelIcon size={16} />,
})

figma.connect(CalendarIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-302', {
  example: () => <CalendarIcon size={16} />,
})

figma.connect(MuteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-132', {
  example: () => <MuteIcon size={16} />,
})

figma.connect(BookmarkSlashFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5421-137', {
  example: () => <BookmarkSlashFillIcon size={16} />,
})

figma.connect(ProjectSymlinkIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4119-126', {
  example: () => <ProjectSymlinkIcon size={16} />,
})

figma.connect(TrashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-28', {
  example: () => <TrashIcon size={16} />,
})

figma.connect(ToolsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-30', {
  example: () => <ToolsIcon size={16} />,
})

figma.connect(GlobeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-198', {
  example: () => <GlobeIcon size={16} />,
})

figma.connect(TabExternalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2975-240', {
  example: () => <TabExternalIcon size={16} />,
})

figma.connect(BeakerIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-319', {
  example: () => <BeakerIcon size={16} />,
})

figma.connect(VideoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1737-14', {
  example: () => <VideoIcon size={16} />,
})

figma.connect(ClockFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4119-128', {
  example: () => <ClockFillIcon size={16} />,
})

figma.connect(MultiSelectIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1666-78', {
  example: () => <MultiSelectIcon size={16} />,
})

figma.connect(RocketIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-82', {
  example: () => <RocketIcon size={16} />,
})

figma.connect(DownloadIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4549-158', {
  example: () => <DownloadIcon size={24} />,
})

figma.connect(CheckboxIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3752-125', {
  example: () => <CheckboxIcon size={16} />,
})

figma.connect(CheckboxIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3752-130', {
  example: () => <CheckboxIcon size={24} />,
})

figma.connect(ShareIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-70', {
  example: () => <ShareIcon size={16} />,
})

figma.connect(RepoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-867', {
  example: () => <RepoIcon size={24} />,
})

figma.connect(ArrowSwitchIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3042-217', {
  example: () => <ArrowSwitchIcon size={16} />,
})

figma.connect(RepoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-92', {
  example: () => <RepoIcon size={16} />,
})

figma.connect(GitCompareIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-950', {
  example: () => <GitCompareIcon size={24} />,
})

figma.connect(VersionsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-907', {
  example: () => <VersionsIcon size={24} />,
})

figma.connect(IssueReopenedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-945', {
  example: () => <IssueReopenedIcon size={24} />,
})

figma.connect(AlertFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2621-75', {
  example: () => <AlertFillIcon size={12} />,
})

figma.connect(GitPullRequestDraftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2059-95', {
  example: () => <GitPullRequestDraftIcon size={24} />,
})

figma.connect(ThreeBarsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-36', {
  example: () => <ThreeBarsIcon size={16} />,
})

figma.connect(FileAddedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3480-124', {
  example: () => <FileAddedIcon size={16} />,
})

figma.connect(FileDiffIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-232', {
  example: () => <FileDiffIcon size={16} />,
})

figma.connect(SmileyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-56', {
  example: () => <SmileyIcon size={16} />,
})

figma.connect(VerifiedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1039', {
  example: () => <VerifiedIcon size={24} />,
})

figma.connect(LinkIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-154', {
  example: () => <LinkIcon size={16} />,
})

figma.connect(ReadIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4297-105', {
  example: () => <ReadIcon size={16} />,
})

figma.connect(FileDirectoryIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3162-228', {
  example: () => <FileDirectoryIcon size={16} />,
})

figma.connect(FileDirectoryIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-933', {
  example: () => <FileDirectoryIcon size={24} />,
})

figma.connect(TagIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-894', {
  example: () => <TagIcon size={24} />,
})

figma.connect(CodeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=183-247', {
  example: () => <CodeIcon size={24} />,
})

figma.connect(PeopleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-116', {
  example: () => <PeopleIcon size={16} />,
})

figma.connect(GitBranchIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-208', {
  example: () => <GitBranchIcon size={16} />,
})

figma.connect(HomeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-184', {
  example: () => <HomeIcon size={16} />,
})

figma.connect(NoteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-130', {
  example: () => <NoteIcon size={16} />,
})

figma.connect(ShieldLockIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-62', {
  example: () => <ShieldLockIcon size={16} />,
})

figma.connect(CodespacesIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1946-77', {
  example: () => <CodespacesIcon size={16} />,
})

figma.connect(VerifiedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-6', {
  example: () => <VerifiedIcon size={16} />,
})

figma.connect(GitCommitIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-206', {
  example: () => <GitCommitIcon size={16} />,
})

figma.connect(BookmarkIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-308', {
  example: () => <BookmarkIcon size={16} />,
})

figma.connect(DotIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-246', {
  example: () => <DotIcon size={16} />,
})

figma.connect(MilestoneIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-136', {
  example: () => <MilestoneIcon size={16} />,
})

figma.connect(DeviceCameraIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5479-552', {
  example: () => <DeviceCameraIcon size={16} />,
})

figma.connect(ChecklistIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-296', {
  example: () => <ChecklistIcon size={16} />,
})

figma.connect(PencilIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-976', {
  example: () => <PencilIcon size={24} />,
})

figma.connect(RepoForkedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-876', {
  example: () => <RepoForkedIcon size={24} />,
})

figma.connect(QuestionIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-98', {
  example: () => <QuestionIcon size={16} />,
})

figma.connect(CheckCircleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=29-0', {
  example: () => <CheckCircleIcon size={16} />,
})

figma.connect(StarIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-982', {
  example: () => <StarIcon size={24} />,
})

figma.connect(PinIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4986-114', {
  example: () => <PinIcon size={16} />,
})

figma.connect(CommentDiscussionIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-272', {
  example: () => <CommentDiscussionIcon size={16} />,
})

figma.connect(LockIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-144', {
  example: () => <LockIcon size={16} />,
})

figma.connect(InfoIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-174', {
  example: () => <InfoIcon size={16} />,
})

figma.connect(GitMergeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-202', {
  example: () => <GitMergeIcon size={16} />,
})

figma.connect(WorkflowIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-2', {
  example: () => <WorkflowIcon size={16} />,
})

figma.connect(TrophyIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4678-122', {
  example: () => <TrophyIcon size={16} />,
})

figma.connect(ShareAndroidIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-68', {
  example: () => <ShareAndroidIcon size={16} />,
})

figma.connect(PulseIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-100', {
  example: () => <PulseIcon size={16} />,
})

figma.connect(CommentIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-274', {
  example: () => <CommentIcon size={16} />,
})

figma.connect(AlertIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-913', {
  example: () => <AlertIcon size={24} />,
})

figma.connect(FileZipIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-224', {
  example: () => <FileZipIcon size={16} />,
})

figma.connect(LogIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2975-234', {
  example: () => <LogIcon size={16} />,
})

figma.connect(LawIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-929', {
  example: () => <LawIcon size={24} />,
})

figma.connect(LawIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-158', {
  example: () => <LawIcon size={16} />,
})

figma.connect(ThumbsupIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-32', {
  example: () => <ThumbsupIcon size={16} />,
})

figma.connect(StrikethroughIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1554-86', {
  example: () => <StrikethroughIcon size={16} />,
})

figma.connect(ThumbsupIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-969', {
  example: () => <ThumbsupIcon size={24} />,
})

figma.connect(BellFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2562-75', {
  example: () => <BellFillIcon size={16} />,
})

figma.connect(HeartFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-977', {
  example: () => <HeartFillIcon size={24} />,
})

figma.connect(BugIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2314-131', {
  example: () => <BugIcon size={24} />,
})

figma.connect(ChecklistIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-920', {
  example: () => <ChecklistIcon size={24} />,
})

figma.connect(CommentDiscussionIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-943', {
  example: () => <CommentDiscussionIcon size={24} />,
})

figma.connect(FileBadgeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5460-483', {
  example: () => <FileBadgeIcon size={24} />,
})

figma.connect(PencilIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-118', {
  example: () => <PencilIcon size={16} />,
})

figma.connect(MarkdownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=23-72', {
  example: () => <MarkdownIcon size={16} />,
})

figma.connect(FoldIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-218', {
  example: () => <FoldIcon size={16} />,
})

figma.connect(PackageIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-126', {
  example: () => <PackageIcon size={16} />,
})

figma.connect(MarkGithubIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-140', {
  example: () => <MarkGithubIcon size={16} />,
})

figma.connect(DeviceCameraIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5479-559', {
  example: () => <DeviceCameraIcon size={24} />,
})

figma.connect(FileDirectoryOpenFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3161-214', {
  example: () => <FileDirectoryOpenFillIcon size={16} />,
})

figma.connect(RelFilePathIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4223-105', {
  example: () => <RelFilePathIcon size={16} />,
})

figma.connect(IssueClosedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-172', {
  example: () => <IssueClosedIcon size={16} />,
})

figma.connect(DuplicateIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2384-80', {
  example: () => <DuplicateIcon size={16} />,
})

figma.connect(FileCodeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=32-99', {
  example: () => <FileCodeIcon size={16} />,
})

figma.connect(ChevronRightIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-924', {
  example: () => <ChevronRightIcon size={24} />,
})

figma.connect(ReadIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4297-111', {
  example: () => <ReadIcon size={24} />,
})

figma.connect(ArrowDownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1038', {
  example: () => <ArrowDownIcon size={24} />,
})

figma.connect(OrganizationIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-128', {
  example: () => <OrganizationIcon size={16} />,
})

figma.connect(StopIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-50', {
  example: () => <StopIcon size={16} />,
})

figma.connect(FileDirectoryFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-230', {
  example: () => <FileDirectoryFillIcon size={16} />,
})

figma.connect(FileBadgeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1102-74', {
  example: () => <FileBadgeIcon size={16} />,
})

figma.connect(CheckIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-919', {
  example: () => <CheckIcon size={24} />,
})

figma.connect(FileDirectoryFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1042', {
  example: () => <FileDirectoryFillIcon size={24} />,
})

figma.connect(ChevronDownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4445-119', {
  example: () => <ChevronDownIcon size={12} />,
})

figma.connect(NoEntryIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2594-82', {
  example: () => <NoEntryIcon size={16} />,
})

figma.connect(CircleSlashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-286', {
  example: () => <CircleSlashIcon size={16} />,
})

figma.connect(ProjectRoadmapIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4119-127', {
  example: () => <ProjectRoadmapIcon size={16} />,
})

figma.connect(GoalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4238-106', {
  example: () => <GoalIcon size={16} />,
})

figma.connect(OrganizationIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-865', {
  example: () => <OrganizationIcon size={24} />,
})

figma.connect(XCircleFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=964-34', {
  example: () => <XCircleFillIcon size={16} />,
})

figma.connect(CheckCircleFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-975', {
  example: () => <CheckCircleFillIcon size={24} />,
})

figma.connect(StackIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2500-98', {
  example: () => <StackIcon size={24} />,
})

figma.connect(DashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=186-7', {
  example: () => <DashIcon size={16} />,
})

figma.connect(IssueClosedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-956', {
  example: () => <IssueClosedIcon size={24} />,
})

figma.connect(LightBulbIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1037', {
  example: () => <LightBulbIcon size={24} />,
})

figma.connect(CopilotErrorIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5199-124', {
  example: () => <CopilotErrorIcon size={16} />,
})

figma.connect(IssueTracksIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4098-111', {
  example: () => <IssueTracksIcon size={16} />,
})

figma.connect(IssueTrackedByIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4098-112', {
  example: () => <IssueTrackedByIcon size={16} />,
})

figma.connect(CopilotWarningIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5199-122', {
  example: () => <CopilotWarningIcon size={16} />,
})

figma.connect(IssueTracksIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4098-109', {
  example: () => <IssueTracksIcon size={16} />,
})

figma.connect(IssueTrackedByIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4098-110', {
  example: () => <IssueTrackedByIcon size={16} />,
})

figma.connect(EyeClosedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-965', {
  example: () => <EyeClosedIcon size={24} />,
})

figma.connect(BookmarkFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5421-130', {
  example: () => <BookmarkFillIcon size={16} />,
})

figma.connect(ListUnorderedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-960', {
  example: () => <ListUnorderedIcon size={24} />,
})

figma.connect(ListUnorderedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-148', {
  example: () => <ListUnorderedIcon size={16} />,
})

figma.connect(SingleSelectIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2062-16', {
  example: () => <SingleSelectIcon size={24} />,
})

figma.connect(XCircleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=210-7', {
  example: () => <XCircleIcon size={24} />,
})

figma.connect(DeviceDesktopIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=32-77', {
  example: () => <DeviceDesktopIcon size={16} />,
})

figma.connect(DiffIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-954', {
  example: () => <DiffIcon size={24} />,
})

figma.connect(FlameIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1050', {
  example: () => <FlameIcon size={24} />,
})

figma.connect(FileSymlinkFileIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-872', {
  example: () => <FileSymlinkFileIcon size={24} />,
})

figma.connect(ProjectIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1007', {
  example: () => <ProjectIcon size={24} />,
})

figma.connect(PasteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-898', {
  example: () => <PasteIcon size={24} />,
})

figma.connect(FlameIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-220', {
  example: () => <FlameIcon size={16} />,
})

figma.connect(TableIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1914-4', {
  example: () => <TableIcon size={24} />,
})

figma.connect(FileSymlinkFileIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-226', {
  example: () => <FileSymlinkFileIcon size={16} />,
})

figma.connect(XCircleFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2621-76', {
  example: () => <XCircleFillIcon size={12} />,
})

figma.connect(CheckCircleFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2617-90', {
  example: () => <CheckCircleFillIcon size={12} />,
})

figma.connect(CpuIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-270', {
  example: () => <CpuIcon size={16} />,
})

figma.connect(DesktopDownloadIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=32-72', {
  example: () => <DesktopDownloadIcon size={16} />,
})

figma.connect(IssueOpenedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1043', {
  example: () => <IssueOpenedIcon size={24} />,
})

figma.connect(DatabaseIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1029', {
  example: () => <DatabaseIcon size={24} />,
})

figma.connect(HeartFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-188', {
  example: () => <HeartFillIcon size={16} />,
})

figma.connect(CodeSquareIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-951', {
  example: () => <CodeSquareIcon size={24} />,
})

figma.connect(PackageIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-934', {
  example: () => <PackageIcon size={24} />,
})

figma.connect(ShieldIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-66', {
  example: () => <ShieldIcon size={16} />,
})

figma.connect(UnfoldIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-16', {
  example: () => <UnfoldIcon size={16} />,
})

figma.connect(PlusCircleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-104', {
  example: () => <PlusCircleIcon size={16} />,
})

figma.connect(StackIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2500-91', {
  example: () => <StackIcon size={16} />,
})

figma.connect(DashIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-992', {
  example: () => <DashIcon size={24} />,
})

figma.connect(ThreeBarsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=5451-237', {
  example: () => <ThreeBarsIcon size={24} />,
})

figma.connect(BookmarkIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-973', {
  example: () => <BookmarkIcon size={24} />,
})

figma.connect(CheckCircleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1005', {
  example: () => <CheckCircleIcon size={24} />,
})

figma.connect(BookIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-983', {
  example: () => <BookIcon size={24} />,
})

figma.connect(GearIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1036', {
  example: () => <GearIcon size={24} />,
})

figma.connect(DotFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-935', {
  example: () => <DotFillIcon size={24} />,
})

figma.connect(DotFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-244', {
  example: () => <DotFillIcon size={16} />,
})

figma.connect(FoldDownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-216', {
  example: () => <FoldDownIcon size={16} />,
})

figma.connect(RepoPushIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-88', {
  example: () => <RepoPushIcon size={16} />,
})

figma.connect(PlayIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-110', {
  example: () => <PlayIcon size={16} />,
})

figma.connect(CodespacesIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=1946-76', {
  example: () => <CodespacesIcon size={24} />,
})

figma.connect(PlusIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-917', {
  example: () => <PlusIcon size={24} />,
})

figma.connect(TriangleDownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-886', {
  example: () => <TriangleDownIcon size={24} />,
})

figma.connect(ShieldIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1026', {
  example: () => <ShieldIcon size={24} />,
})

figma.connect(GlobeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1021', {
  example: () => <GlobeIcon size={24} />,
})

figma.connect(PlusCircleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1004', {
  example: () => <PlusCircleIcon size={24} />,
})

figma.connect(FileSubmoduleIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-228', {
  example: () => <FileSubmoduleIcon size={16} />,
})

figma.connect(MilestoneIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-904', {
  example: () => <MilestoneIcon size={24} />,
})

figma.connect(PinIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4986-124', {
  example: () => <PinIcon size={24} />,
})

figma.connect(HomeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-964', {
  example: () => <HomeIcon size={24} />,
})

figma.connect(ZapIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=966-29', {
  example: () => <ZapIcon size={24} />,
})

figma.connect(SearchIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-955', {
  example: () => <SearchIcon size={24} />,
})

figma.connect(GraphIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-875', {
  example: () => <GraphIcon size={24} />,
})

figma.connect(StarFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-52', {
  example: () => <StarFillIcon size={16} />,
})

figma.connect(GrabberIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-196', {
  example: () => <GrabberIcon size={16} />,
})

figma.connect(FoldUpIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-214', {
  example: () => <FoldUpIcon size={16} />,
})

figma.connect(RepoLockedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3161-219', {
  example: () => <RepoLockedIcon size={16} />,
})

figma.connect(CrossReferenceIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-266', {
  example: () => <CrossReferenceIcon size={16} />,
})

figma.connect(LinkExternalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-152', {
  example: () => <LinkExternalIcon size={16} />,
})

figma.connect(ArrowRightIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-323', {
  example: () => <ArrowRightIcon size={16} />,
})

figma.connect(LogoGithubIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=181-78', {
  example: () => <LogoGithubIcon size={16} />,
})

figma.connect(TerminalIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-38', {
  example: () => <TerminalIcon size={16} />,
})

figma.connect(SparkleFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4525-109', {
  example: () => <SparkleFillIcon size={16} />,
})

figma.connect(CheckCircleFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-298', {
  example: () => <CheckCircleFillIcon size={16} />,
})

figma.connect(EyeClosedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-236', {
  example: () => <EyeClosedIcon size={16} />,
})

figma.connect(CalendarIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-869', {
  example: () => <CalendarIcon size={24} />,
})

figma.connect(CodeSquareIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-276', {
  example: () => <CodeSquareIcon size={16} />,
})

figma.connect(DiffIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-84', {
  example: () => <DiffIcon size={16} />,
})

figma.connect(DiffModifiedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-252', {
  example: () => <DiffModifiedIcon size={16} />,
})

figma.connect(ChevronUpIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-288', {
  example: () => <ChevronUpIcon size={16} />,
})

figma.connect(CopilotIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3567-115', {
  example: () => <CopilotIcon size={24} />,
})

figma.connect(CopilotIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4977-111', {
  example: () => <CopilotIcon size={16} />,
})

figma.connect(TriangleDownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-26', {
  example: () => <TriangleDownIcon size={16} />,
})

figma.connect(ColumnsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2062-9', {
  example: () => <ColumnsIcon size={16} />,
})

figma.connect(ArrowUpRightIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=246-91', {
  example: () => <ArrowUpRightIcon size={16} />,
})

figma.connect(LightBulbIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-156', {
  example: () => <LightBulbIcon size={16} />,
})

figma.connect(ClockFillIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4119-124', {
  example: () => <ClockFillIcon size={24} />,
})

figma.connect(ClockIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-1022', {
  example: () => <ClockIcon size={24} />,
})

figma.connect(CheckIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-300', {
  example: () => <CheckIcon size={16} />,
})

figma.connect(SyncIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=179-949', {
  example: () => <SyncIcon size={24} />,
})

figma.connect(UploadIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4549-152', {
  example: () => <UploadIcon size={16} />,
})

figma.connect(PasteIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-284', {
  example: () => <PasteIcon size={16} />,
})

figma.connect(FilterIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-222', {
  example: () => <FilterIcon size={16} />,
})

figma.connect(PlusIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-106', {
  example: () => <PlusIcon size={16} />,
})

figma.connect(AppsIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2976-223', {
  example: () => <AppsIcon size={16} />,
})

figma.connect(BellIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-316', {
  example: () => <BellIcon size={16} />,
})

figma.connect(InboxIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-178', {
  example: () => <InboxIcon size={16} />,
})

figma.connect(PaperclipIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=3751-104', {
  example: () => <PaperclipIcon size={16} />,
})

figma.connect(ArrowLeftIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-325', {
  example: () => <ArrowLeftIcon size={16} />,
})

figma.connect(XIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=4834-124', {
  example: () => <XIcon size={12} />,
})

figma.connect(XIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-0', {
  example: () => <XIcon size={16} />,
})

figma.connect(StopwatchIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-48', {
  example: () => <StopwatchIcon size={16} />,
})

figma.connect(GitPullRequestIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-200', {
  example: () => <GitPullRequestIcon size={16} />,
})

figma.connect(GitPullRequestClosedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=2059-88', {
  example: () => <GitPullRequestClosedIcon size={16} />,
})

figma.connect(ThumbsdownIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-34', {
  example: () => <ThumbsdownIcon size={16} />,
})

figma.connect(CodeIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-280', {
  example: () => <CodeIcon size={16} />,
})

figma.connect(IssueOpenedIcon, 'https://figma.com/file/1ljgTFkT5NKNRfq5hw07JQ/?node-id=13-170', {
  example: () => <IssueOpenedIcon size={16} />,
})
