name: Check for changeset

on:
  pull_request:
    types:
      # On by default if you specify no types.
      - 'opened'
      - 'reopened'
      - 'synchronize'
      # For `skip-label` only.
      - 'labeled'
      - 'unlabeled'

jobs:
  check-for-changeset:
    name: Check for changeset
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: 'Check for changeset'
        uses: ./.github/actions/check-for-changed-files
        with:
          file-pattern: '.changeset/*.md'
          skip-label: 'skip changeset'
          failure-message: 'No changeset found. If these changes should not result in a new version, apply the ${skip-label} label to this pull request. If these changes should result in a version bump, please add a changeset https://git.io/J6QvQ'
          token: ${{ github.token }}
