name: CI
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    branches:
      - main
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check for unformatted files
        run: pnpm run format:diff

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint JavaScript
        run: pnpm run lint
      - name: Lint CSS
        run: pnpm run lint:css
      - name: Lint markdown
        run: pnpm run lint:md
      - name: Lint npm packages
        run: pnpm exec turbo run lint:npm
      - name: Check className test coverage
        run: pnpm run test:classname-coverage

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react-version: ['react-18', 'react-19']
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Set up turbo cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.job }}-${{ matrix.react-version }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.job }}-${{ matrix.react-version }}-
            ${{ runner.os }}-turbo-${{ github.job }}-
            ${{ runner.os }}-turbo-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - if: ${{ matrix.react-version == 'react-19' }}
        run: node script/setup-react-19.mts
      - name: Build
        run: pnpm run build
        continue-on-error: ${{ matrix.react-version == 'react-19' }}
      - name: Run tests defined in vitest
        uses: docker://mcr.microsoft.com/playwright:v1.60.0-jammy
        with:
          args: ./node_modules/.bin/vitest run

  type-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react-version: ['react-18', 'react-19']
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Set up turbo cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.job }}-${{ matrix.react-version }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.job }}-${{ matrix.react-version }}-
            ${{ runner.os }}-turbo-${{ github.job }}-
            ${{ runner.os }}-turbo-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - if: ${{ matrix.react-version == 'react-19' }}
        run: node script/setup-react-19.mts
      - name: Build project
        run: pnpm run build
        continue-on-error: ${{ matrix.react-version == 'react-19' }}
      - name: Type check
        run: pnpm run type-check
        continue-on-error: ${{ matrix.react-version == 'react-19' }}

  examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react-version: ['react-18', 'react-19']
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Set up turbo cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.job }}-${{ matrix.react-version }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.job }}-${{ matrix.react-version }}-
            ${{ runner.os }}-turbo-${{ github.job }}-
            ${{ runner.os }}-turbo-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - if: ${{ matrix.react-version == 'react-19' }}
        run: node script/setup-react-19.mts
      - name: Build
        run: pnpm exec turbo run build
        continue-on-error: ${{ matrix.react-version == 'react-19' }}

  build-components-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Set up turbo cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.job }}-default-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.job }}-default-
            ${{ runner.os }}-turbo-${{ github.job }}-
            ${{ runner.os }}-turbo-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build storybook to generate story IDs
        run: pnpm exec turbo run build:storybook --filter=@primer/react
      - name: Build components.json
        run: pnpm exec tsx script/components-json/build.ts --storybook-data 'storybook-static/index.json'
        working-directory: packages/react
      - name: Build hooks.json
        run: pnpm exec tsx script/hooks-json/build.ts
        working-directory: packages/react

  sizes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Set up turbo cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.job }}-default-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.job }}-default-
            ${{ runner.os }}-turbo-${{ github.job }}-
            ${{ runner.os }}-turbo-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Get export sizes
        run: node packages/react/script/get-export-sizes.cjs
