name: Migration Status
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  react-compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.27.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run migration script
        run: node script/react-compiler-migration-status.mts >> $GITHUB_STEP_SUMMARY

  ts-docgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.27.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build doc-gen
        run: pnpm run build -w @primer/doc-gen
      - name: Run migration script
        run: node script/ts-docs-status.mts >> $GITHUB_STEP_SUMMARY
