name: Primer Bot
on:
  repository_dispatch:
    types: [primer-bot-question]
  workflow_dispatch:
    inputs:
      question:
        type: string
        description: 'Question to ask the Primer bot'
        required: true

permissions: {}

jobs:
  answer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build @primer/react
        run: npm run build -w packages/react

      - name: Answer question
        env:
          GITHUB_MODELS_TOKEN: ${{ secrets.MODELS_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: npx tsx packages/primer-api/src/action.ts
