name: Report workflow failures

on:
  workflow_run:
    workflows:
      - Codespaces Prebuilds
    types:
      - completed

permissions: {}

jobs:
  create-issue:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      issues: write
    steps:
      - name: Create issue
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const workflowRun = context.payload.workflow_run;
            const workflow = await github.rest.actions.getWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflowRun.workflow_id,
            });
            const jobs = await github.paginate(
              github.rest.actions.listJobsForWorkflowRun,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: workflowRun.id,
                filter: 'latest',
                per_page: 100,
              },
            );
            const failedJobs = jobs.filter((job) => job.conclusion === 'failure');
            const failedJobLinks = failedJobs.map(
              (job) => `[${job.name}](${job.html_url})`,
            );

            if (failedJobLinks.length === 0) {
              failedJobLinks.push(`[Failed run](${workflowRun.html_url})`);
            }

            const body = [
              `- ${workflow.data.name}: ${failedJobLinks.join(', ')}`,
              '',
              '@github/primer-engineering, please investigate and fix.',
            ].join('\n');

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Investigate GitHub workflow failure',
              body,
            });
