name: vrt
on:
  pull_request:
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-snapshots:
    if: contains(github.event.pull_request.labels.*.name, 'update snapshots')
    runs-on: ubuntu-latest
    steps:
      - name: Save Pull Request info
        run: |
          mkdir PR
          echo $NUMBER > ./PR/number
        env:
          NUMBER: ${{ github.event.number }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: pull-request
          path: ./PR
          retention-days: 1

  upload-snapshots:
    needs: update-snapshots
    runs-on: ubuntu-latest-8-cores
    strategy:
      fail-fast: true
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Set up pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Set up turbo cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.job }}-shard-${{ matrix.shard }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.job }}-shard-${{ matrix.shard }}-
            ${{ runner.os }}-turbo-${{ github.job }}-
            ${{ runner.os }}-turbo-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build storybook
        run: npx turbo run build:storybook
      - name: Run storybook
        id: storybook
        run: |
          npx serve -l 6006 packages/react/storybook-static &
          pid=$!
          echo "pid=$pid" >> $GITHUB_OUTPUT
          sleep 5
      - name: Run styled-react storybook
        id: styled-react-storybook
        run: |
          npx serve -l 6007 packages/styled-react/storybook-static &
          pid=$!
          echo "pid=$pid" >> $GITHUB_OUTPUT
          sleep 5
      - name: Run VRT
        uses: docker://mcr.microsoft.com/playwright:v1.60.0-jammy
        env:
          STORYBOOK_URL: 'http://172.17.0.1:6006'
          STYLED_REACT_STORYBOOK_URL: 'http://172.17.0.1:6007'
        with:
          args: npx playwright test --grep @vrt --update-snapshots --shard="${{ matrix.shard }}/${{ strategy.job-total }}"
      - name: Stop storybook
        run: kill ${{ steps.storybook.outputs.pid }}
      - name: Stop styled-react storybook
        run: kill ${{ steps.styled-react-storybook.outputs.pid }}
      - name: Create snapshots.zip
        run: |
          if [[ ! -z  $(git ls-files --others --exclude-standard --modified) ]]; then
            git ls-files --others --exclude-standard --modified | zip snapshots -@
          fi
      - name: Upload snapshots
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: snapshots-${{ matrix.shard }}
          path: snapshots.zip
          retention-days: 1
          if-no-files-found: ignore
